# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/polly/Downloads/GitHub_Workspace/AutoConfiguration/AutoConfigGUI/IndexWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IndexWindow(object):
    def setupUi(self, IndexWindow):
        IndexWindow.setObjectName("IndexWindow")
        IndexWindow.setEnabled(True)
        IndexWindow.resize(846, 614)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(IndexWindow.sizePolicy().hasHeightForWidth())
        IndexWindow.setSizePolicy(sizePolicy)
        IndexWindow.setTabletTracking(False)
        IndexWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(IndexWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout_menu = QtWidgets.QHBoxLayout()
        self.layout_menu.setObjectName("layout_menu")
        self.btn_get_license = QtWidgets.QPushButton(self.centralwidget)
        self.btn_get_license.setAutoFillBackground(True)
        self.btn_get_license.setStyleSheet("color: rgb(0, 0, 255);")
        self.btn_get_license.setAutoDefault(False)
        self.btn_get_license.setDefault(False)
        self.btn_get_license.setFlat(True)
        self.btn_get_license.setObjectName("btn_get_license")
        self.layout_menu.addWidget(self.btn_get_license)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_menu.addItem(spacerItem)
        self.btn_import = QtWidgets.QPushButton(self.centralwidget)
        self.btn_import.setObjectName("btn_import")
        self.layout_menu.addWidget(self.btn_import)
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setObjectName("btn_save")
        self.layout_menu.addWidget(self.btn_save)
        self.btn_save_as = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_as.setObjectName("btn_save_as")
        self.layout_menu.addWidget(self.btn_save_as)
        self.btn_run = QtWidgets.QPushButton(self.centralwidget)
        self.btn_run.setObjectName("btn_run")
        self.layout_menu.addWidget(self.btn_run)
        self.verticalLayout_2.addLayout(self.layout_menu)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.tab_box = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_box.setEnabled(True)
        self.tab_box.setTabletTracking(False)
        self.tab_box.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_box.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_box.setIconSize(QtCore.QSize(16, 16))
        self.tab_box.setElideMode(QtCore.Qt.ElideNone)
        self.tab_box.setUsesScrollButtons(True)
        self.tab_box.setDocumentMode(False)
        self.tab_box.setTabsClosable(False)
        self.tab_box.setMovable(False)
        self.tab_box.setTabBarAutoHide(False)
        self.tab_box.setObjectName("tab_box")
        self.tab_config_1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_config_1.sizePolicy().hasHeightForWidth())
        self.tab_config_1.setSizePolicy(sizePolicy)
        self.tab_config_1.setObjectName("tab_config_1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_config_1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea_1 = QtWidgets.QScrollArea(self.tab_config_1)
        self.scrollArea_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_1.setWidgetResizable(True)
        self.scrollArea_1.setObjectName("scrollArea_1")
        self.scrollAreaWidgetContents_1 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_1.setGeometry(QtCore.QRect(0, 0, 822, 256))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_1.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_1.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_1.setObjectName("scrollAreaWidgetContents_1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_cfg1_PRE = QtWidgets.QLabel(self.scrollAreaWidgetContents_1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg1_PRE.setFont(font)
        self.lbl_cfg1_PRE.setObjectName("lbl_cfg1_PRE")
        self.gridLayout.addWidget(self.lbl_cfg1_PRE, 5, 0, 1, 1)
        self.list_cfg1_PM = QtWidgets.QListWidget(self.scrollAreaWidgetContents_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_cfg1_PM.sizePolicy().hasHeightForWidth())
        self.list_cfg1_PM.setSizePolicy(sizePolicy)
        self.list_cfg1_PM.setMinimumSize(QtCore.QSize(0, 150))
        self.list_cfg1_PM.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.list_cfg1_PM.setObjectName("list_cfg1_PM")
        self.gridLayout.addWidget(self.list_cfg1_PM, 1, 2, 3, 1)
        self.lbl_cfg1_PF = QtWidgets.QLabel(self.scrollAreaWidgetContents_1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg1_PF.setFont(font)
        self.lbl_cfg1_PF.setObjectName("lbl_cfg1_PF")
        self.gridLayout.addWidget(self.lbl_cfg1_PF, 4, 0, 1, 1)
        self.ledt_cfg1_PF = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_1)
        self.ledt_cfg1_PF.setReadOnly(True)
        self.ledt_cfg1_PF.setObjectName("ledt_cfg1_PF")
        self.gridLayout.addWidget(self.ledt_cfg1_PF, 4, 2, 1, 1)
        self.cbox_cfg1_TM = QtWidgets.QComboBox(self.scrollAreaWidgetContents_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_cfg1_TM.sizePolicy().hasHeightForWidth())
        self.cbox_cfg1_TM.setSizePolicy(sizePolicy)
        self.cbox_cfg1_TM.setMinimumSize(QtCore.QSize(150, 0))
        self.cbox_cfg1_TM.setObjectName("cbox_cfg1_TM")
        self.cbox_cfg1_TM.addItem("")
        self.cbox_cfg1_TM.addItem("")
        self.cbox_cfg1_TM.addItem("")
        self.gridLayout.addWidget(self.cbox_cfg1_TM, 0, 2, 1, 2)
        self.btn_cfg1_PM_clear = QtWidgets.QPushButton(self.scrollAreaWidgetContents_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cfg1_PM_clear.sizePolicy().hasHeightForWidth())
        self.btn_cfg1_PM_clear.setSizePolicy(sizePolicy)
        self.btn_cfg1_PM_clear.setSizeIncrement(QtCore.QSize(0, 1))
        self.btn_cfg1_PM_clear.setObjectName("btn_cfg1_PM_clear")
        self.gridLayout.addWidget(self.btn_cfg1_PM_clear, 3, 3, 1, 1)
        self.lbl_cfg1_PM = QtWidgets.QLabel(self.scrollAreaWidgetContents_1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg1_PM.setFont(font)
        self.lbl_cfg1_PM.setObjectName("lbl_cfg1_PM")
        self.gridLayout.addWidget(self.lbl_cfg1_PM, 2, 0, 1, 1)
        self.ledt_cfg1_PRE = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_1)
        self.ledt_cfg1_PRE.setReadOnly(True)
        self.ledt_cfg1_PRE.setObjectName("ledt_cfg1_PRE")
        self.gridLayout.addWidget(self.ledt_cfg1_PRE, 5, 2, 1, 1)
        self.btn_cfg1_PRE = QtWidgets.QPushButton(self.scrollAreaWidgetContents_1)
        self.btn_cfg1_PRE.setObjectName("btn_cfg1_PRE")
        self.gridLayout.addWidget(self.btn_cfg1_PRE, 5, 3, 1, 1)
        self.btn_cfg1_PF = QtWidgets.QPushButton(self.scrollAreaWidgetContents_1)
        self.btn_cfg1_PF.setObjectName("btn_cfg1_PF")
        self.gridLayout.addWidget(self.btn_cfg1_PF, 4, 3, 1, 1)
        self.btn_cfg1_PM_add = QtWidgets.QPushButton(self.scrollAreaWidgetContents_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cfg1_PM_add.sizePolicy().hasHeightForWidth())
        self.btn_cfg1_PM_add.setSizePolicy(sizePolicy)
        self.btn_cfg1_PM_add.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_cfg1_PM_add.setSizeIncrement(QtCore.QSize(0, 1))
        self.btn_cfg1_PM_add.setObjectName("btn_cfg1_PM_add")
        self.gridLayout.addWidget(self.btn_cfg1_PM_add, 1, 3, 1, 1)
        self.lbl_cfg1_TM = QtWidgets.QLabel(self.scrollAreaWidgetContents_1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg1_TM.setFont(font)
        self.lbl_cfg1_TM.setObjectName("lbl_cfg1_TM")
        self.gridLayout.addWidget(self.lbl_cfg1_TM, 0, 0, 1, 1)
        self.btn_cfg1_PM_del = QtWidgets.QPushButton(self.scrollAreaWidgetContents_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cfg1_PM_del.sizePolicy().hasHeightForWidth())
        self.btn_cfg1_PM_del.setSizePolicy(sizePolicy)
        self.btn_cfg1_PM_del.setSizeIncrement(QtCore.QSize(0, 1))
        self.btn_cfg1_PM_del.setObjectName("btn_cfg1_PM_del")
        self.gridLayout.addWidget(self.btn_cfg1_PM_del, 2, 3, 1, 1)
        self.verticalLayout_1.addLayout(self.gridLayout)
        self.horizontalLayout_6.addLayout(self.verticalLayout_1)
        self.scrollArea_1.setWidget(self.scrollAreaWidgetContents_1)
        self.verticalLayout_4.addWidget(self.scrollArea_1)
        self.tab_box.addTab(self.tab_config_1, "")
        self.tab_config_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_config_2.sizePolicy().hasHeightForWidth())
        self.tab_config_2.setSizePolicy(sizePolicy)
        self.tab_config_2.setObjectName("tab_config_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_config_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_config_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea_2.setStyleSheet("")
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollArea_2.setLineWidth(1)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 805, 738))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2_1.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2_1.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_2_1.setSpacing(0)
        self.verticalLayout_2_1.setObjectName("verticalLayout_2_1")
        self.btn_cfg2_group_1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cfg2_group_1.sizePolicy().hasHeightForWidth())
        self.btn_cfg2_group_1.setSizePolicy(sizePolicy)
        self.btn_cfg2_group_1.setMinimumSize(QtCore.QSize(0, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.btn_cfg2_group_1.setFont(font)
        self.btn_cfg2_group_1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_cfg2_group_1.setAutoFillBackground(False)
        self.btn_cfg2_group_1.setStyleSheet("QPushButton{text-align:left; border:none;margin-bottom:2px;}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon_show.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/icon_hide.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_cfg2_group_1.setIcon(icon)
        self.btn_cfg2_group_1.setCheckable(True)
        self.btn_cfg2_group_1.setAutoDefault(False)
        self.btn_cfg2_group_1.setDefault(False)
        self.btn_cfg2_group_1.setFlat(False)
        self.btn_cfg2_group_1.setObjectName("btn_cfg2_group_1")
        self.verticalLayout_2_1.addWidget(self.btn_cfg2_group_1)
        self.frame_group_1 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_group_1.sizePolicy().hasHeightForWidth())
        self.frame_group_1.setSizePolicy(sizePolicy)
        self.frame_group_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_group_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_group_1.setObjectName("frame_group_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_group_1)
        self.horizontalLayout_2.setContentsMargins(10, 2, 0, 8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.layout_data = QtWidgets.QGridLayout()
        self.layout_data.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_data.setObjectName("layout_data")
        self.cbox_cfg2_NMMC = QtWidgets.QComboBox(self.frame_group_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_cfg2_NMMC.sizePolicy().hasHeightForWidth())
        self.cbox_cfg2_NMMC.setSizePolicy(sizePolicy)
        self.cbox_cfg2_NMMC.setMinimumSize(QtCore.QSize(150, 0))
        self.cbox_cfg2_NMMC.setObjectName("cbox_cfg2_NMMC")
        self.cbox_cfg2_NMMC.addItem("")
        self.cbox_cfg2_NMMC.addItem("")
        self.cbox_cfg2_NMMC.addItem("")
        self.cbox_cfg2_NMMC.addItem("")
        self.layout_data.addWidget(self.cbox_cfg2_NMMC, 1, 1, 1, 1)
        self.lbl_cfg2_NMMC = QtWidgets.QLabel(self.frame_group_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_cfg2_NMMC.sizePolicy().hasHeightForWidth())
        self.lbl_cfg2_NMMC.setSizePolicy(sizePolicy)
        self.lbl_cfg2_NMMC.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg2_NMMC.setFont(font)
        self.lbl_cfg2_NMMC.setObjectName("lbl_cfg2_NMMC")
        self.layout_data.addWidget(self.lbl_cfg2_NMMC, 1, 0, 1, 1)
        self.lbl_cfg2_TD = QtWidgets.QLabel(self.frame_group_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_cfg2_TD.sizePolicy().hasHeightForWidth())
        self.lbl_cfg2_TD.setSizePolicy(sizePolicy)
        self.lbl_cfg2_TD.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg2_TD.setFont(font)
        self.lbl_cfg2_TD.setObjectName("lbl_cfg2_TD")
        self.layout_data.addWidget(self.lbl_cfg2_TD, 2, 0, 1, 1)
        self.lbl_cfg2_NE = QtWidgets.QLabel(self.frame_group_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_cfg2_NE.sizePolicy().hasHeightForWidth())
        self.lbl_cfg2_NE.setSizePolicy(sizePolicy)
        self.lbl_cfg2_NE.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg2_NE.setFont(font)
        self.lbl_cfg2_NE.setObjectName("lbl_cfg2_NE")
        self.layout_data.addWidget(self.lbl_cfg2_NE, 0, 0, 1, 1)
        self.lbl_cfg2_NMM = QtWidgets.QLabel(self.frame_group_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_cfg2_NMM.sizePolicy().hasHeightForWidth())
        self.lbl_cfg2_NMM.setSizePolicy(sizePolicy)
        self.lbl_cfg2_NMM.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg2_NMM.setFont(font)
        self.lbl_cfg2_NMM.setObjectName("lbl_cfg2_NMM")
        self.layout_data.addWidget(self.lbl_cfg2_NMM, 4, 0, 1, 1)
        self.cbox_cfg2_NE = QtWidgets.QComboBox(self.frame_group_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_cfg2_NE.sizePolicy().hasHeightForWidth())
        self.cbox_cfg2_NE.setSizePolicy(sizePolicy)
        self.cbox_cfg2_NE.setMinimumSize(QtCore.QSize(150, 0))
        self.cbox_cfg2_NE.setObjectName("cbox_cfg2_NE")
        self.cbox_cfg2_NE.addItem("")
        self.layout_data.addWidget(self.cbox_cfg2_NE, 0, 1, 1, 1)
        self.cbox_cfg2_TD = QtWidgets.QComboBox(self.frame_group_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_cfg2_TD.sizePolicy().hasHeightForWidth())
        self.cbox_cfg2_TD.setSizePolicy(sizePolicy)
        self.cbox_cfg2_TD.setMinimumSize(QtCore.QSize(150, 0))
        self.cbox_cfg2_TD.setObjectName("cbox_cfg2_TD")
        self.cbox_cfg2_TD.addItem("")
        self.cbox_cfg2_TD.addItem("")
        self.cbox_cfg2_TD.addItem("")
        self.layout_data.addWidget(self.cbox_cfg2_TD, 2, 1, 1, 1)
        self.cbox_cfg2_NMM = QtWidgets.QComboBox(self.frame_group_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_cfg2_NMM.sizePolicy().hasHeightForWidth())
        self.cbox_cfg2_NMM.setSizePolicy(sizePolicy)
        self.cbox_cfg2_NMM.setMinimumSize(QtCore.QSize(150, 0))
        self.cbox_cfg2_NMM.setObjectName("cbox_cfg2_NMM")
        self.cbox_cfg2_NMM.addItem("")
        self.cbox_cfg2_NMM.addItem("")
        self.cbox_cfg2_NMM.addItem("")
        self.cbox_cfg2_NMM.addItem("")
        self.layout_data.addWidget(self.cbox_cfg2_NMM, 4, 1, 1, 1)
        self.gbox_MultiSelect_2 = QtWidgets.QFrame(self.frame_group_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbox_MultiSelect_2.sizePolicy().hasHeightForWidth())
        self.gbox_MultiSelect_2.setSizePolicy(sizePolicy)
        self.gbox_MultiSelect_2.setMinimumSize(QtCore.QSize(0, 250))
        self.gbox_MultiSelect_2.setObjectName("gbox_MultiSelect_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.gbox_MultiSelect_2)
        self.horizontalLayout_7.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbl_cfg2_NM = QtWidgets.QLabel(self.gbox_MultiSelect_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_cfg2_NM.sizePolicy().hasHeightForWidth())
        self.lbl_cfg2_NM.setSizePolicy(sizePolicy)
        self.lbl_cfg2_NM.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg2_NM.setFont(font)
        self.lbl_cfg2_NM.setObjectName("lbl_cfg2_NM")
        self.horizontalLayout_7.addWidget(self.lbl_cfg2_NM)
        self.splitter_3 = QtWidgets.QSplitter(self.gbox_MultiSelect_2)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.label_3 = QtWidgets.QLabel(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.splitter_3)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.list_cfg2_NMF = QtWidgets.QListWidget(self.gbox_MultiSelect_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_cfg2_NMF.sizePolicy().hasHeightForWidth())
        self.list_cfg2_NMF.setSizePolicy(sizePolicy)
        self.list_cfg2_NMF.setMinimumSize(QtCore.QSize(0, 100))
        self.list_cfg2_NMF.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_cfg2_NMF.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.list_cfg2_NMF.setObjectName("list_cfg2_NMF")
        item = QtWidgets.QListWidgetItem()
        self.list_cfg2_NMF.addItem(item)
        self.verticalLayout_9.addWidget(self.list_cfg2_NMF)
        self.list_cfg2_NMV = QtWidgets.QListWidget(self.gbox_MultiSelect_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_cfg2_NMV.sizePolicy().hasHeightForWidth())
        self.list_cfg2_NMV.setSizePolicy(sizePolicy)
        self.list_cfg2_NMV.setMinimumSize(QtCore.QSize(0, 100))
        self.list_cfg2_NMV.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_cfg2_NMV.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.list_cfg2_NMV.setObjectName("list_cfg2_NMV")
        item = QtWidgets.QListWidgetItem()
        self.list_cfg2_NMV.addItem(item)
        self.verticalLayout_9.addWidget(self.list_cfg2_NMV)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.splitter_5 = QtWidgets.QSplitter(self.gbox_MultiSelect_2)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.layoutWidget_2 = QtWidgets.QWidget(self.splitter_5)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.btn_cfg2_f2u = QtWidgets.QToolButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cfg2_f2u.sizePolicy().hasHeightForWidth())
        self.btn_cfg2_f2u.setSizePolicy(sizePolicy)
        self.btn_cfg2_f2u.setObjectName("btn_cfg2_f2u")
        self.verticalLayout_10.addWidget(self.btn_cfg2_f2u)
        self.btn_cfg2_u2f = QtWidgets.QToolButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cfg2_u2f.sizePolicy().hasHeightForWidth())
        self.btn_cfg2_u2f.setSizePolicy(sizePolicy)
        self.btn_cfg2_u2f.setObjectName("btn_cfg2_u2f")
        self.verticalLayout_10.addWidget(self.btn_cfg2_u2f)
        self.layoutWidget_3 = QtWidgets.QWidget(self.splitter_5)
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.btn_cfg2_v2u = QtWidgets.QToolButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cfg2_v2u.sizePolicy().hasHeightForWidth())
        self.btn_cfg2_v2u.setSizePolicy(sizePolicy)
        self.btn_cfg2_v2u.setObjectName("btn_cfg2_v2u")
        self.verticalLayout_11.addWidget(self.btn_cfg2_v2u)
        self.btn_cfg2_u2v = QtWidgets.QToolButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cfg2_u2v.sizePolicy().hasHeightForWidth())
        self.btn_cfg2_u2v.setSizePolicy(sizePolicy)
        self.btn_cfg2_u2v.setObjectName("btn_cfg2_u2v")
        self.verticalLayout_11.addWidget(self.btn_cfg2_u2v)
        self.horizontalLayout_7.addWidget(self.splitter_5)
        self.list_cfg2_NM = QtWidgets.QListWidget(self.gbox_MultiSelect_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_cfg2_NM.sizePolicy().hasHeightForWidth())
        self.list_cfg2_NM.setSizePolicy(sizePolicy)
        self.list_cfg2_NM.setMinimumSize(QtCore.QSize(0, 180))
        self.list_cfg2_NM.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_cfg2_NM.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.list_cfg2_NM.setObjectName("list_cfg2_NM")
        item = QtWidgets.QListWidgetItem()
        self.list_cfg2_NM.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_cfg2_NM.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_cfg2_NM.addItem(item)
        self.horizontalLayout_7.addWidget(self.list_cfg2_NM)
        self.layout_data.addWidget(self.gbox_MultiSelect_2, 3, 0, 1, 3)
        self.horizontalLayout_2.addLayout(self.layout_data)
        self.verticalLayout_2_1.addWidget(self.frame_group_1)
        self.btn_cfg2_group_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cfg2_group_2.sizePolicy().hasHeightForWidth())
        self.btn_cfg2_group_2.setSizePolicy(sizePolicy)
        self.btn_cfg2_group_2.setMinimumSize(QtCore.QSize(0, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.btn_cfg2_group_2.setFont(font)
        self.btn_cfg2_group_2.setStyleSheet("QPushButton{text-align:left; border:none;margin-bottom:2px;}")
        self.btn_cfg2_group_2.setIcon(icon)
        self.btn_cfg2_group_2.setCheckable(True)
        self.btn_cfg2_group_2.setFlat(False)
        self.btn_cfg2_group_2.setObjectName("btn_cfg2_group_2")
        self.verticalLayout_2_1.addWidget(self.btn_cfg2_group_2)
        self.frame_group_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_group_2.sizePolicy().hasHeightForWidth())
        self.frame_group_2.setSizePolicy(sizePolicy)
        self.frame_group_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_group_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_group_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_group_2.setObjectName("frame_group_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_group_2)
        self.horizontalLayout_3.setContentsMargins(10, 2, 0, 8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbl_cfg2_US = QtWidgets.QLabel(self.frame_group_2)
        self.lbl_cfg2_US.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg2_US.setFont(font)
        self.lbl_cfg2_US.setObjectName("lbl_cfg2_US")
        self.gridLayout_3.addWidget(self.lbl_cfg2_US, 0, 0, 1, 1)
        self.ledt_cfg2_UA = QtWidgets.QLineEdit(self.frame_group_2)
        self.ledt_cfg2_UA.setReadOnly(False)
        self.ledt_cfg2_UA.setObjectName("ledt_cfg2_UA")
        self.gridLayout_3.addWidget(self.ledt_cfg2_UA, 1, 1, 1, 1)
        self.lbl_cfg2_UC = QtWidgets.QLabel(self.frame_group_2)
        self.lbl_cfg2_UC.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg2_UC.setFont(font)
        self.lbl_cfg2_UC.setObjectName("lbl_cfg2_UC")
        self.gridLayout_3.addWidget(self.lbl_cfg2_UC, 4, 0, 1, 1)
        self.lbl_cfg2_UA = QtWidgets.QLabel(self.frame_group_2)
        self.lbl_cfg2_UA.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg2_UA.setFont(font)
        self.lbl_cfg2_UA.setObjectName("lbl_cfg2_UA")
        self.gridLayout_3.addWidget(self.lbl_cfg2_UA, 1, 0, 1, 1)
        self.ledt_cfg2_ULA = QtWidgets.QLineEdit(self.frame_group_2)
        self.ledt_cfg2_ULA.setReadOnly(False)
        self.ledt_cfg2_ULA.setObjectName("ledt_cfg2_ULA")
        self.gridLayout_3.addWidget(self.ledt_cfg2_ULA, 5, 1, 1, 1)
        self.lbl_cfg2_ULL = QtWidgets.QLabel(self.frame_group_2)
        self.lbl_cfg2_ULL.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg2_ULL.setFont(font)
        self.lbl_cfg2_ULL.setObjectName("lbl_cfg2_ULL")
        self.gridLayout_3.addWidget(self.lbl_cfg2_ULL, 2, 0, 1, 1)
        self.lbl_cfg2_ULA = QtWidgets.QLabel(self.frame_group_2)
        self.lbl_cfg2_ULA.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg2_ULA.setFont(font)
        self.lbl_cfg2_ULA.setObjectName("lbl_cfg2_ULA")
        self.gridLayout_3.addWidget(self.lbl_cfg2_ULA, 5, 0, 1, 1)
        self.ledt_cfg2_US = QtWidgets.QLineEdit(self.frame_group_2)
        self.ledt_cfg2_US.setReadOnly(False)
        self.ledt_cfg2_US.setObjectName("ledt_cfg2_US")
        self.gridLayout_3.addWidget(self.ledt_cfg2_US, 0, 1, 1, 1)
        self.ledt_cfg2_ULL = QtWidgets.QLineEdit(self.frame_group_2)
        self.ledt_cfg2_ULL.setReadOnly(False)
        self.ledt_cfg2_ULL.setObjectName("ledt_cfg2_ULL")
        self.gridLayout_3.addWidget(self.ledt_cfg2_ULL, 2, 1, 1, 1)
        self.ledt_cfg2_UC = QtWidgets.QLineEdit(self.frame_group_2)
        self.ledt_cfg2_UC.setReadOnly(False)
        self.ledt_cfg2_UC.setObjectName("ledt_cfg2_UC")
        self.gridLayout_3.addWidget(self.ledt_cfg2_UC, 4, 1, 1, 1)
        self.lbl_cfg2_ULU = QtWidgets.QLabel(self.frame_group_2)
        self.lbl_cfg2_ULU.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg2_ULU.setFont(font)
        self.lbl_cfg2_ULU.setObjectName("lbl_cfg2_ULU")
        self.gridLayout_3.addWidget(self.lbl_cfg2_ULU, 3, 0, 1, 1)
        self.ledt_cfg2_ULU = QtWidgets.QLineEdit(self.frame_group_2)
        self.ledt_cfg2_ULU.setReadOnly(False)
        self.ledt_cfg2_ULU.setObjectName("ledt_cfg2_ULU")
        self.gridLayout_3.addWidget(self.ledt_cfg2_ULU, 3, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        self.verticalLayout_2_1.addWidget(self.frame_group_2)
        self.btn_cfg2_group_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cfg2_group_3.sizePolicy().hasHeightForWidth())
        self.btn_cfg2_group_3.setSizePolicy(sizePolicy)
        self.btn_cfg2_group_3.setMinimumSize(QtCore.QSize(0, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.btn_cfg2_group_3.setFont(font)
        self.btn_cfg2_group_3.setStyleSheet("QPushButton{text-align:left; border:none;margin-bottom:2px;}")
        self.btn_cfg2_group_3.setIcon(icon)
        self.btn_cfg2_group_3.setCheckable(True)
        self.btn_cfg2_group_3.setFlat(False)
        self.btn_cfg2_group_3.setObjectName("btn_cfg2_group_3")
        self.verticalLayout_2_1.addWidget(self.btn_cfg2_group_3)
        self.frame_group_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_group_3.sizePolicy().hasHeightForWidth())
        self.frame_group_3.setSizePolicy(sizePolicy)
        self.frame_group_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_group_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_group_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_group_3.setObjectName("frame_group_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_group_3)
        self.horizontalLayout_8.setContentsMargins(10, 2, 0, 8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.ledt_cfg2_PTF = QtWidgets.QLineEdit(self.frame_group_3)
        self.ledt_cfg2_PTF.setReadOnly(False)
        self.ledt_cfg2_PTF.setObjectName("ledt_cfg2_PTF")
        self.gridLayout_6.addWidget(self.ledt_cfg2_PTF, 1, 1, 1, 1)
        self.lbl_cfg2_FP = QtWidgets.QLabel(self.frame_group_3)
        self.lbl_cfg2_FP.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg2_FP.setFont(font)
        self.lbl_cfg2_FP.setObjectName("lbl_cfg2_FP")
        self.gridLayout_6.addWidget(self.lbl_cfg2_FP, 4, 0, 1, 1)
        self.lbl_cfg2_TA = QtWidgets.QLabel(self.frame_group_3)
        self.lbl_cfg2_TA.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg2_TA.setFont(font)
        self.lbl_cfg2_TA.setObjectName("lbl_cfg2_TA")
        self.gridLayout_6.addWidget(self.lbl_cfg2_TA, 2, 0, 1, 1)
        self.lbl_cfg2_NT = QtWidgets.QLabel(self.frame_group_3)
        self.lbl_cfg2_NT.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg2_NT.setFont(font)
        self.lbl_cfg2_NT.setObjectName("lbl_cfg2_NT")
        self.gridLayout_6.addWidget(self.lbl_cfg2_NT, 3, 0, 1, 1)
        self.lbl_cfg2_PTP = QtWidgets.QLabel(self.frame_group_3)
        self.lbl_cfg2_PTP.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg2_PTP.setFont(font)
        self.lbl_cfg2_PTP.setObjectName("lbl_cfg2_PTP")
        self.gridLayout_6.addWidget(self.lbl_cfg2_PTP, 0, 0, 1, 1)
        self.ledt_cfg2_PTP = QtWidgets.QLineEdit(self.frame_group_3)
        self.ledt_cfg2_PTP.setReadOnly(False)
        self.ledt_cfg2_PTP.setObjectName("ledt_cfg2_PTP")
        self.gridLayout_6.addWidget(self.ledt_cfg2_PTP, 0, 1, 1, 1)
        self.ledt_cfg2_FP = QtWidgets.QLineEdit(self.frame_group_3)
        self.ledt_cfg2_FP.setReadOnly(False)
        self.ledt_cfg2_FP.setObjectName("ledt_cfg2_FP")
        self.gridLayout_6.addWidget(self.ledt_cfg2_FP, 4, 1, 1, 1)
        self.lbl_cfg2_PTF = QtWidgets.QLabel(self.frame_group_3)
        self.lbl_cfg2_PTF.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg2_PTF.setFont(font)
        self.lbl_cfg2_PTF.setObjectName("lbl_cfg2_PTF")
        self.gridLayout_6.addWidget(self.lbl_cfg2_PTF, 1, 0, 1, 1)
        self.cbox_cfg2_TA = QtWidgets.QComboBox(self.frame_group_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_cfg2_TA.sizePolicy().hasHeightForWidth())
        self.cbox_cfg2_TA.setSizePolicy(sizePolicy)
        self.cbox_cfg2_TA.setMinimumSize(QtCore.QSize(150, 0))
        self.cbox_cfg2_TA.setObjectName("cbox_cfg2_TA")
        self.cbox_cfg2_TA.addItem("")
        self.gridLayout_6.addWidget(self.cbox_cfg2_TA, 2, 1, 1, 1)
        self.cbox_cfg2_NT = QtWidgets.QComboBox(self.frame_group_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_cfg2_NT.sizePolicy().hasHeightForWidth())
        self.cbox_cfg2_NT.setSizePolicy(sizePolicy)
        self.cbox_cfg2_NT.setMinimumSize(QtCore.QSize(150, 0))
        self.cbox_cfg2_NT.setObjectName("cbox_cfg2_NT")
        self.cbox_cfg2_NT.addItem("")
        self.cbox_cfg2_NT.addItem("")
        self.cbox_cfg2_NT.addItem("")
        self.cbox_cfg2_NT.addItem("")
        self.cbox_cfg2_NT.addItem("")
        self.gridLayout_6.addWidget(self.cbox_cfg2_NT, 3, 1, 1, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout_6)
        self.verticalLayout_2_1.addWidget(self.frame_group_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2_1.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_2_1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.tab_box.addTab(self.tab_config_2, "")
        self.tab_summary = QtWidgets.QWidget()
        self.tab_summary.setObjectName("tab_summary")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_summary)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_summary)
        self.scrollArea_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 265, 468))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_summary_group_1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_summary_group_1.sizePolicy().hasHeightForWidth())
        self.btn_summary_group_1.setSizePolicy(sizePolicy)
        self.btn_summary_group_1.setMinimumSize(QtCore.QSize(0, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.btn_summary_group_1.setFont(font)
        self.btn_summary_group_1.setStyleSheet("QPushButton{text-align:left; border:none;margin-bottom:2px;}")
        self.btn_summary_group_1.setIcon(icon)
        self.btn_summary_group_1.setCheckable(True)
        self.btn_summary_group_1.setFlat(False)
        self.btn_summary_group_1.setObjectName("btn_summary_group_1")
        self.verticalLayout_5.addWidget(self.btn_summary_group_1)
        self.tbl_cfg1 = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_cfg1.sizePolicy().hasHeightForWidth())
        self.tbl_cfg1.setSizePolicy(sizePolicy)
        self.tbl_cfg1.setStyleSheet("QTableWidget{margin-left:20px;}")
        self.tbl_cfg1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tbl_cfg1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tbl_cfg1.setMidLineWidth(0)
        self.tbl_cfg1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tbl_cfg1.setAutoScroll(True)
        self.tbl_cfg1.setAutoScrollMargin(16)
        self.tbl_cfg1.setAlternatingRowColors(False)
        self.tbl_cfg1.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbl_cfg1.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_cfg1.setWordWrap(True)
        self.tbl_cfg1.setCornerButtonEnabled(True)
        self.tbl_cfg1.setObjectName("tbl_cfg1")
        self.tbl_cfg1.setColumnCount(2)
        self.tbl_cfg1.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cfg1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cfg1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cfg1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cfg1.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cfg1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cfg1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cfg1.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cfg1.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cfg1.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cfg1.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cfg1.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cfg1.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cfg1.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cfg1.setItem(3, 1, item)
        self.tbl_cfg1.horizontalHeader().setCascadingSectionResizes(True)
        self.tbl_cfg1.horizontalHeader().setDefaultSectionSize(150)
        self.tbl_cfg1.horizontalHeader().setMinimumSectionSize(50)
        self.tbl_cfg1.horizontalHeader().setSortIndicatorShown(False)
        self.tbl_cfg1.horizontalHeader().setStretchLastSection(True)
        self.tbl_cfg1.verticalHeader().setVisible(False)
        self.tbl_cfg1.verticalHeader().setCascadingSectionResizes(False)
        self.tbl_cfg1.verticalHeader().setDefaultSectionSize(25)
        self.verticalLayout_5.addWidget(self.tbl_cfg1)
        self.btn_summary_group_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_summary_group_2.sizePolicy().hasHeightForWidth())
        self.btn_summary_group_2.setSizePolicy(sizePolicy)
        self.btn_summary_group_2.setMinimumSize(QtCore.QSize(0, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.btn_summary_group_2.setFont(font)
        self.btn_summary_group_2.setStyleSheet("QPushButton{text-align:left; border:none;margin-bottom:2px;}")
        self.btn_summary_group_2.setIcon(icon)
        self.btn_summary_group_2.setCheckable(True)
        self.btn_summary_group_2.setFlat(False)
        self.btn_summary_group_2.setObjectName("btn_summary_group_2")
        self.verticalLayout_5.addWidget(self.btn_summary_group_2)
        self.tbl_cfg2 = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_cfg2.sizePolicy().hasHeightForWidth())
        self.tbl_cfg2.setSizePolicy(sizePolicy)
        self.tbl_cfg2.setStyleSheet("QTableWidget{margin-left:20px;}")
        self.tbl_cfg2.setAlternatingRowColors(False)
        self.tbl_cfg2.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbl_cfg2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_cfg2.setWordWrap(True)
        self.tbl_cfg2.setCornerButtonEnabled(True)
        self.tbl_cfg2.setObjectName("tbl_cfg2")
        self.tbl_cfg2.setColumnCount(2)
        self.tbl_cfg2.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cfg2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cfg2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cfg2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cfg2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cfg2.setItem(0, 1, item)
        self.tbl_cfg2.horizontalHeader().setCascadingSectionResizes(True)
        self.tbl_cfg2.horizontalHeader().setDefaultSectionSize(150)
        self.tbl_cfg2.horizontalHeader().setMinimumSectionSize(50)
        self.tbl_cfg2.horizontalHeader().setSortIndicatorShown(False)
        self.tbl_cfg2.horizontalHeader().setStretchLastSection(True)
        self.tbl_cfg2.verticalHeader().setVisible(False)
        self.tbl_cfg2.verticalHeader().setCascadingSectionResizes(False)
        self.tbl_cfg2.verticalHeader().setDefaultSectionSize(25)
        self.verticalLayout_5.addWidget(self.tbl_cfg2)
        self.btn_summary_group_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_summary_group_3.sizePolicy().hasHeightForWidth())
        self.btn_summary_group_3.setSizePolicy(sizePolicy)
        self.btn_summary_group_3.setMinimumSize(QtCore.QSize(0, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.btn_summary_group_3.setFont(font)
        self.btn_summary_group_3.setStyleSheet("QPushButton{text-align:left; border:none;margin-bottom:2px;}")
        self.btn_summary_group_3.setIcon(icon)
        self.btn_summary_group_3.setCheckable(True)
        self.btn_summary_group_3.setFlat(False)
        self.btn_summary_group_3.setObjectName("btn_summary_group_3")
        self.verticalLayout_5.addWidget(self.btn_summary_group_3)
        self.tbl_cfg3 = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_cfg3.sizePolicy().hasHeightForWidth())
        self.tbl_cfg3.setSizePolicy(sizePolicy)
        self.tbl_cfg3.setStyleSheet("QTableWidget{margin-left:20px;}")
        self.tbl_cfg3.setAlternatingRowColors(False)
        self.tbl_cfg3.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbl_cfg3.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_cfg3.setWordWrap(True)
        self.tbl_cfg3.setCornerButtonEnabled(True)
        self.tbl_cfg3.setObjectName("tbl_cfg3")
        self.tbl_cfg3.setColumnCount(2)
        self.tbl_cfg3.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cfg3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cfg3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cfg3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cfg3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_cfg3.setItem(0, 1, item)
        self.tbl_cfg3.horizontalHeader().setCascadingSectionResizes(True)
        self.tbl_cfg3.horizontalHeader().setDefaultSectionSize(150)
        self.tbl_cfg3.horizontalHeader().setMinimumSectionSize(50)
        self.tbl_cfg3.horizontalHeader().setSortIndicatorShown(False)
        self.tbl_cfg3.horizontalHeader().setStretchLastSection(True)
        self.tbl_cfg3.verticalHeader().setVisible(False)
        self.tbl_cfg3.verticalHeader().setCascadingSectionResizes(False)
        self.tbl_cfg3.verticalHeader().setDefaultSectionSize(25)
        self.verticalLayout_5.addWidget(self.tbl_cfg3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_4.addWidget(self.scrollArea_3)
        self.tab_box.addTab(self.tab_summary, "")
        self.verticalLayout_2.addWidget(self.tab_box)
        self.layout_status = QtWidgets.QHBoxLayout()
        self.layout_status.setObjectName("layout_status")
        self.lbl_status = QtWidgets.QLabel(self.centralwidget)
        self.lbl_status.setObjectName("lbl_status")
        self.layout_status.addWidget(self.lbl_status)
        self.pbar_status = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbar_status.sizePolicy().hasHeightForWidth())
        self.pbar_status.setSizePolicy(sizePolicy)
        self.pbar_status.setBaseSize(QtCore.QSize(0, 0))
        self.pbar_status.setProperty("value", 0)
        self.pbar_status.setTextVisible(False)
        self.pbar_status.setInvertedAppearance(False)
        self.pbar_status.setObjectName("pbar_status")
        self.layout_status.addWidget(self.pbar_status)
        self.verticalLayout_2.addLayout(self.layout_status)
        IndexWindow.setCentralWidget(self.centralwidget)
        self.action = QtWidgets.QAction(IndexWindow)
        self.action.setObjectName("action")

        self.retranslateUi(IndexWindow)
        self.tab_box.setCurrentIndex(0)
        self.btn_cfg2_group_1.toggled['bool'].connect(self.frame_group_1.setHidden)
        self.btn_cfg2_group_2.toggled['bool'].connect(self.frame_group_2.setHidden)
        self.btn_cfg2_group_3.toggled['bool'].connect(self.frame_group_3.setHidden)
        QtCore.QMetaObject.connectSlotsByName(IndexWindow)

    def retranslateUi(self, IndexWindow):
        _translate = QtCore.QCoreApplication.translate
        IndexWindow.setWindowTitle(_translate("IndexWindow", "AutoConfiguration(已授权)"))
        self.btn_get_license.setToolTip(_translate("IndexWindow", "免费申请，请放心使用"))
        self.btn_get_license.setText(_translate("IndexWindow", "Register"))
        self.btn_import.setText(_translate("IndexWindow", "Import"))
        self.btn_save.setText(_translate("IndexWindow", "Save"))
        self.btn_save_as.setText(_translate("IndexWindow", "Save as"))
        self.btn_run.setText(_translate("IndexWindow", "Run"))
        self.lbl_cfg1_PRE.setText(_translate("IndexWindow", "PATH_RESULT_EXPORT"))
        self.lbl_cfg1_PF.setText(_translate("IndexWindow", "PATH_FASTA"))
        self.cbox_cfg1_TM.setItemText(0, _translate("IndexWindow", "raw"))
        self.cbox_cfg1_TM.setItemText(1, _translate("IndexWindow", "ms1"))
        self.cbox_cfg1_TM.setItemText(2, _translate("IndexWindow", "mgf"))
        self.btn_cfg1_PM_clear.setText(_translate("IndexWindow", "Clear"))
        self.lbl_cfg1_PM.setText(_translate("IndexWindow", "PATH_MS2"))
        self.btn_cfg1_PRE.setText(_translate("IndexWindow", "Browser"))
        self.btn_cfg1_PF.setText(_translate("IndexWindow", "Browser"))
        self.btn_cfg1_PM_add.setText(_translate("IndexWindow", "Add"))
        self.lbl_cfg1_TM.setText(_translate("IndexWindow", "TYPE_MS2"))
        self.btn_cfg1_PM_del.setText(_translate("IndexWindow", "Del"))
        self.tab_box.setTabText(self.tab_box.indexOf(self.tab_config_1), _translate("IndexWindow", "ConfigOne"))
        self.btn_cfg2_group_1.setText(_translate("IndexWindow", "Group 1"))
        self.cbox_cfg2_NMMC.setItemText(0, _translate("IndexWindow", "1"))
        self.cbox_cfg2_NMMC.setItemText(1, _translate("IndexWindow", "2"))
        self.cbox_cfg2_NMMC.setItemText(2, _translate("IndexWindow", "3"))
        self.cbox_cfg2_NMMC.setItemText(3, _translate("IndexWindow", "4"))
        self.lbl_cfg2_NMMC.setText(_translate("IndexWindow", "NUMBER_MAX_MISS_CLS"))
        self.lbl_cfg2_TD.setText(_translate("IndexWindow", "TYPE_DIGEST"))
        self.lbl_cfg2_NE.setText(_translate("IndexWindow", "NAME_ENZYME"))
        self.lbl_cfg2_NMM.setText(_translate("IndexWindow", "NUMBER_MAX_MOD"))
        self.cbox_cfg2_NE.setItemText(0, _translate("IndexWindow", "trpysin"))
        self.cbox_cfg2_TD.setItemText(0, _translate("IndexWindow", "specific"))
        self.cbox_cfg2_TD.setItemText(1, _translate("IndexWindow", "semi-specific"))
        self.cbox_cfg2_TD.setItemText(2, _translate("IndexWindow", "none-specific"))
        self.cbox_cfg2_NMM.setItemText(0, _translate("IndexWindow", "1"))
        self.cbox_cfg2_NMM.setItemText(1, _translate("IndexWindow", "2"))
        self.cbox_cfg2_NMM.setItemText(2, _translate("IndexWindow", "3"))
        self.cbox_cfg2_NMM.setItemText(3, _translate("IndexWindow", "4"))
        self.lbl_cfg2_NM.setText(_translate("IndexWindow", "NAME_MOD"))
        self.label_3.setText(_translate("IndexWindow", "Fixed"))
        self.label_4.setText(_translate("IndexWindow", "Variable"))
        __sortingEnabled = self.list_cfg2_NMF.isSortingEnabled()
        self.list_cfg2_NMF.setSortingEnabled(False)
        item = self.list_cfg2_NMF.item(0)
        item.setText(_translate("IndexWindow", "项目1"))
        self.list_cfg2_NMF.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.list_cfg2_NMV.isSortingEnabled()
        self.list_cfg2_NMV.setSortingEnabled(False)
        item = self.list_cfg2_NMV.item(0)
        item.setText(_translate("IndexWindow", "项目2"))
        self.list_cfg2_NMV.setSortingEnabled(__sortingEnabled)
        self.btn_cfg2_f2u.setText(_translate("IndexWindow", "->"))
        self.btn_cfg2_u2f.setText(_translate("IndexWindow", "<-"))
        self.btn_cfg2_v2u.setText(_translate("IndexWindow", "->"))
        self.btn_cfg2_u2v.setText(_translate("IndexWindow", "<-"))
        __sortingEnabled = self.list_cfg2_NM.isSortingEnabled()
        self.list_cfg2_NM.setSortingEnabled(False)
        item = self.list_cfg2_NM.item(0)
        item.setText(_translate("IndexWindow", "项目3"))
        item = self.list_cfg2_NM.item(1)
        item.setText(_translate("IndexWindow", "项目4"))
        item = self.list_cfg2_NM.item(2)
        item.setText(_translate("IndexWindow", "项目5"))
        self.list_cfg2_NM.setSortingEnabled(__sortingEnabled)
        self.btn_cfg2_group_2.setText(_translate("IndexWindow", "Group 2"))
        self.lbl_cfg2_US.setText(_translate("IndexWindow", "UAA_SEQ"))
        self.lbl_cfg2_UC.setText(_translate("IndexWindow", "UAA_COM"))
        self.lbl_cfg2_UA.setText(_translate("IndexWindow", "UAA_AA"))
        self.lbl_cfg2_ULL.setText(_translate("IndexWindow", "UAA_LEN_LOW"))
        self.lbl_cfg2_ULA.setText(_translate("IndexWindow", "UAA_LINKED_AA"))
        self.lbl_cfg2_ULU.setText(_translate("IndexWindow", "UAA_LEN_UP"))
        self.btn_cfg2_group_3.setText(_translate("IndexWindow", "Group 3"))
        self.lbl_cfg2_FP.setText(_translate("IndexWindow", "FDR_PSM"))
        self.lbl_cfg2_TA.setText(_translate("IndexWindow", "TYPE_ACTIVATION"))
        self.lbl_cfg2_NT.setText(_translate("IndexWindow", "NUMBER_THREAD"))
        self.lbl_cfg2_PTP.setText(_translate("IndexWindow", "PPM_TOL_PRECURSOR"))
        self.lbl_cfg2_PTF.setText(_translate("IndexWindow", "PPM_TOL_FRAGMENT"))
        self.cbox_cfg2_TA.setItemText(0, _translate("IndexWindow", "HCD"))
        self.cbox_cfg2_NT.setItemText(0, _translate("IndexWindow", "1"))
        self.cbox_cfg2_NT.setItemText(1, _translate("IndexWindow", "2"))
        self.cbox_cfg2_NT.setItemText(2, _translate("IndexWindow", "4"))
        self.cbox_cfg2_NT.setItemText(3, _translate("IndexWindow", "8"))
        self.cbox_cfg2_NT.setItemText(4, _translate("IndexWindow", "16"))
        self.tab_box.setTabText(self.tab_box.indexOf(self.tab_config_2), _translate("IndexWindow", "ConfigTwo"))
        self.btn_summary_group_1.setText(_translate("IndexWindow", "ConfigOne"))
        item = self.tbl_cfg1.verticalHeaderItem(0)
        item.setText(_translate("IndexWindow", "1"))
        item = self.tbl_cfg1.verticalHeaderItem(1)
        item.setText(_translate("IndexWindow", "2"))
        item = self.tbl_cfg1.verticalHeaderItem(2)
        item.setText(_translate("IndexWindow", "3"))
        item = self.tbl_cfg1.verticalHeaderItem(3)
        item.setText(_translate("IndexWindow", "4"))
        item = self.tbl_cfg1.horizontalHeaderItem(0)
        item.setText(_translate("IndexWindow", "Property"))
        item = self.tbl_cfg1.horizontalHeaderItem(1)
        item.setText(_translate("IndexWindow", "Value"))
        __sortingEnabled = self.tbl_cfg1.isSortingEnabled()
        self.tbl_cfg1.setSortingEnabled(False)
        item = self.tbl_cfg1.item(0, 0)
        item.setText(_translate("IndexWindow", "TYPE_MS2"))
        item = self.tbl_cfg1.item(0, 1)
        item.setText(_translate("IndexWindow", "-"))
        item = self.tbl_cfg1.item(1, 0)
        item.setText(_translate("IndexWindow", "PATH_MS2"))
        item = self.tbl_cfg1.item(1, 1)
        item.setText(_translate("IndexWindow", "-"))
        item = self.tbl_cfg1.item(2, 0)
        item.setText(_translate("IndexWindow", "PATH_FASTA"))
        item = self.tbl_cfg1.item(2, 1)
        item.setText(_translate("IndexWindow", "-"))
        item = self.tbl_cfg1.item(3, 0)
        item.setText(_translate("IndexWindow", "PATH_RESULT_EXPORT"))
        item = self.tbl_cfg1.item(3, 1)
        item.setText(_translate("IndexWindow", "-"))
        self.tbl_cfg1.setSortingEnabled(__sortingEnabled)
        self.btn_summary_group_2.setText(_translate("IndexWindow", "ConfigTwo"))
        item = self.tbl_cfg2.verticalHeaderItem(0)
        item.setText(_translate("IndexWindow", "1"))
        item = self.tbl_cfg2.horizontalHeaderItem(0)
        item.setText(_translate("IndexWindow", "Property"))
        item = self.tbl_cfg2.horizontalHeaderItem(1)
        item.setText(_translate("IndexWindow", "Value"))
        __sortingEnabled = self.tbl_cfg2.isSortingEnabled()
        self.tbl_cfg2.setSortingEnabled(False)
        item = self.tbl_cfg2.item(0, 0)
        item.setText(_translate("IndexWindow", "123"))
        item = self.tbl_cfg2.item(0, 1)
        item.setText(_translate("IndexWindow", "123"))
        self.tbl_cfg2.setSortingEnabled(__sortingEnabled)
        self.btn_summary_group_3.setText(_translate("IndexWindow", "Others"))
        item = self.tbl_cfg3.verticalHeaderItem(0)
        item.setText(_translate("IndexWindow", "1"))
        item = self.tbl_cfg3.horizontalHeaderItem(0)
        item.setText(_translate("IndexWindow", "Property"))
        item = self.tbl_cfg3.horizontalHeaderItem(1)
        item.setText(_translate("IndexWindow", "Value"))
        __sortingEnabled = self.tbl_cfg3.isSortingEnabled()
        self.tbl_cfg3.setSortingEnabled(False)
        item = self.tbl_cfg3.item(0, 0)
        item.setText(_translate("IndexWindow", "123"))
        item = self.tbl_cfg3.item(0, 1)
        item.setText(_translate("IndexWindow", "123"))
        self.tbl_cfg3.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("IndexWindow", "Save"))
        self.pushButton_3.setText(_translate("IndexWindow", "Run"))
        self.pushButton_2.setText(_translate("IndexWindow", "Stop"))
        self.tab_box.setTabText(self.tab_box.indexOf(self.tab_summary), _translate("IndexWindow", "Summary"))
        self.lbl_status.setText(_translate("IndexWindow", "运行状态"))
        self.pbar_status.setFormat(_translate("IndexWindow", "%p%"))
        self.action.setText(_translate("IndexWindow", "软件注册"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IndexWindow = QtWidgets.QMainWindow()
    ui = Ui_IndexWindow()
    ui.setupUi(IndexWindow)
    IndexWindow.show()
    sys.exit(app.exec_())
