# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Polly\Eric_Workspace\AutoConfigGUI\IndexWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IndexWindow(object):
    def setupUi(self, IndexWindow):
        IndexWindow.setObjectName("IndexWindow")
        IndexWindow.setEnabled(True)
        IndexWindow.resize(896, 673)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(IndexWindow.sizePolicy().hasHeightForWidth())
        IndexWindow.setSizePolicy(sizePolicy)
        IndexWindow.setTabletTracking(False)
        IndexWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(IndexWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout_menu = QtWidgets.QHBoxLayout()
        self.layout_menu.setObjectName("layout_menu")
        self.btn_get_license = QtWidgets.QPushButton(self.centralwidget)
        self.btn_get_license.setAutoFillBackground(True)
        self.btn_get_license.setStyleSheet("color: rgb(0, 0, 255);")
        self.btn_get_license.setAutoDefault(False)
        self.btn_get_license.setDefault(False)
        self.btn_get_license.setFlat(True)
        self.btn_get_license.setObjectName("btn_get_license")
        self.layout_menu.addWidget(self.btn_get_license)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_menu.addItem(spacerItem)
        self.btn_import = QtWidgets.QPushButton(self.centralwidget)
        self.btn_import.setObjectName("btn_import")
        self.layout_menu.addWidget(self.btn_import)
        self.btn_export = QtWidgets.QPushButton(self.centralwidget)
        self.btn_export.setObjectName("btn_export")
        self.layout_menu.addWidget(self.btn_export)
        self.verticalLayout_2.addLayout(self.layout_menu)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.tab_box = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_box.setEnabled(True)
        self.tab_box.setTabletTracking(False)
        self.tab_box.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_box.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_box.setIconSize(QtCore.QSize(16, 16))
        self.tab_box.setElideMode(QtCore.Qt.ElideNone)
        self.tab_box.setUsesScrollButtons(True)
        self.tab_box.setDocumentMode(False)
        self.tab_box.setTabsClosable(False)
        self.tab_box.setMovable(False)
        self.tab_box.setTabBarAutoHide(False)
        self.tab_box.setObjectName("tab_box")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(14, 0, 827, 720))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setContentsMargins(-1, -1, 9, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_cfg_data = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/show.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cfg_data.setIcon(icon)
        self.btn_cfg_data.setAutoDefault(False)
        self.btn_cfg_data.setDefault(False)
        self.btn_cfg_data.setFlat(False)
        self.btn_cfg_data.setObjectName("btn_cfg_data")
        self.verticalLayout.addWidget(self.btn_cfg_data)
        self.frame_data = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_data.sizePolicy().hasHeightForWidth())
        self.frame_data.setSizePolicy(sizePolicy)
        self.frame_data.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_data.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_data.setObjectName("frame_data")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_data)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.layout_data = QtWidgets.QGridLayout()
        self.layout_data.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_data.setObjectName("layout_data")
        self.lbl_data_TM = QtWidgets.QLabel(self.frame_data)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_data_TM.setFont(font)
        self.lbl_data_TM.setObjectName("lbl_data_TM")
        self.layout_data.addWidget(self.lbl_data_TM, 0, 0, 1, 1)
        self.ledt_data_TM = QtWidgets.QLineEdit(self.frame_data)
        self.ledt_data_TM.setReadOnly(False)
        self.ledt_data_TM.setObjectName("ledt_data_TM")
        self.layout_data.addWidget(self.ledt_data_TM, 0, 1, 1, 1)
        self.lbl_data_PM = QtWidgets.QLabel(self.frame_data)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_data_PM.setFont(font)
        self.lbl_data_PM.setObjectName("lbl_data_PM")
        self.layout_data.addWidget(self.lbl_data_PM, 1, 0, 1, 1)
        self.ledt_data_PM = QtWidgets.QLineEdit(self.frame_data)
        self.ledt_data_PM.setReadOnly(True)
        self.ledt_data_PM.setObjectName("ledt_data_PM")
        self.layout_data.addWidget(self.ledt_data_PM, 1, 1, 1, 1)
        self.btn_data_PM = QtWidgets.QPushButton(self.frame_data)
        self.btn_data_PM.setObjectName("btn_data_PM")
        self.layout_data.addWidget(self.btn_data_PM, 1, 2, 1, 1)
        self.lbl_data_PF = QtWidgets.QLabel(self.frame_data)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_data_PF.setFont(font)
        self.lbl_data_PF.setObjectName("lbl_data_PF")
        self.layout_data.addWidget(self.lbl_data_PF, 2, 0, 1, 1)
        self.ledt_data_PF = QtWidgets.QLineEdit(self.frame_data)
        self.ledt_data_PF.setReadOnly(True)
        self.ledt_data_PF.setObjectName("ledt_data_PF")
        self.layout_data.addWidget(self.ledt_data_PF, 2, 1, 1, 1)
        self.btn_data_PF = QtWidgets.QPushButton(self.frame_data)
        self.btn_data_PF.setObjectName("btn_data_PF")
        self.layout_data.addWidget(self.btn_data_PF, 2, 2, 1, 1)
        self.lbl_data_PFE = QtWidgets.QLabel(self.frame_data)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_data_PFE.setFont(font)
        self.lbl_data_PFE.setObjectName("lbl_data_PFE")
        self.layout_data.addWidget(self.lbl_data_PFE, 3, 0, 1, 1)
        self.ledt_data_PFE = QtWidgets.QLineEdit(self.frame_data)
        self.ledt_data_PFE.setReadOnly(True)
        self.ledt_data_PFE.setObjectName("ledt_data_PFE")
        self.layout_data.addWidget(self.ledt_data_PFE, 3, 1, 1, 1)
        self.btn_data_PFE = QtWidgets.QPushButton(self.frame_data)
        self.btn_data_PFE.setObjectName("btn_data_PFE")
        self.layout_data.addWidget(self.btn_data_PFE, 3, 2, 1, 1)
        self.lbl_data_PRE = QtWidgets.QLabel(self.frame_data)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_data_PRE.setFont(font)
        self.lbl_data_PRE.setObjectName("lbl_data_PRE")
        self.layout_data.addWidget(self.lbl_data_PRE, 4, 0, 1, 1)
        self.ledt_data_PRE = QtWidgets.QLineEdit(self.frame_data)
        self.ledt_data_PRE.setReadOnly(True)
        self.ledt_data_PRE.setObjectName("ledt_data_PRE")
        self.layout_data.addWidget(self.ledt_data_PRE, 4, 1, 1, 1)
        self.btn_data_PRE = QtWidgets.QPushButton(self.frame_data)
        self.btn_data_PRE.setObjectName("btn_data_PRE")
        self.layout_data.addWidget(self.btn_data_PRE, 4, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.layout_data)
        self.verticalLayout.addWidget(self.frame_data)
        self.btn_cfg_biology = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_cfg_biology.setObjectName("btn_cfg_biology")
        self.verticalLayout.addWidget(self.btn_cfg_biology)
        self.frame_biology = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_biology.sizePolicy().hasHeightForWidth())
        self.frame_biology.setSizePolicy(sizePolicy)
        self.frame_biology.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_biology.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_biology.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_biology.setObjectName("frame_biology")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_biology)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cbox_bio_TD = QtWidgets.QComboBox(self.frame_biology)
        self.cbox_bio_TD.setObjectName("cbox_bio_TD")
        self.cbox_bio_TD.addItem("")
        self.cbox_bio_TD.addItem("")
        self.cbox_bio_TD.addItem("")
        self.gridLayout_3.addWidget(self.cbox_bio_TD, 1, 1, 1, 1)
        self.lbl_bio_PT = QtWidgets.QLabel(self.frame_biology)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_bio_PT.setFont(font)
        self.lbl_bio_PT.setObjectName("lbl_bio_PT")
        self.gridLayout_3.addWidget(self.lbl_bio_PT, 2, 0, 1, 1)
        self.lbl_bio_TD = QtWidgets.QLabel(self.frame_biology)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_bio_TD.setFont(font)
        self.lbl_bio_TD.setObjectName("lbl_bio_TD")
        self.gridLayout_3.addWidget(self.lbl_bio_TD, 1, 0, 1, 1)
        self.lbl_bio_NE = QtWidgets.QLabel(self.frame_biology)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_bio_NE.setFont(font)
        self.lbl_bio_NE.setObjectName("lbl_bio_NE")
        self.gridLayout_3.addWidget(self.lbl_bio_NE, 0, 0, 1, 1)
        self.ledt_bio_PT = QtWidgets.QLineEdit(self.frame_biology)
        self.ledt_bio_PT.setReadOnly(True)
        self.ledt_bio_PT.setObjectName("ledt_bio_PT")
        self.gridLayout_3.addWidget(self.ledt_bio_PT, 2, 1, 1, 1)
        self.btn_bio_PT = QtWidgets.QPushButton(self.frame_biology)
        self.btn_bio_PT.setObjectName("btn_bio_PT")
        self.gridLayout_3.addWidget(self.btn_bio_PT, 2, 2, 1, 1)
        self.ledt_bio_NE = QtWidgets.QLineEdit(self.frame_biology)
        self.ledt_bio_NE.setReadOnly(False)
        self.ledt_bio_NE.setObjectName("ledt_bio_NE")
        self.gridLayout_3.addWidget(self.ledt_bio_NE, 0, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        self.verticalLayout.addWidget(self.frame_biology)
        self.btn_cfg_mass = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_cfg_mass.setObjectName("btn_cfg_mass")
        self.verticalLayout.addWidget(self.btn_cfg_mass)
        self.frame_mass = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_mass.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_mass.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_mass.setObjectName("frame_mass")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_mass)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gbox_MultiSelect = QtWidgets.QGroupBox(self.frame_mass)
        self.gbox_MultiSelect.setObjectName("gbox_MultiSelect")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.gbox_MultiSelect)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.list_mass_selected = QtWidgets.QListWidget(self.gbox_MultiSelect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_mass_selected.sizePolicy().hasHeightForWidth())
        self.list_mass_selected.setSizePolicy(sizePolicy)
        self.list_mass_selected.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_mass_selected.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.list_mass_selected.setObjectName("list_mass_selected")
        item = QtWidgets.QListWidgetItem()
        self.list_mass_selected.addItem(item)
        self.gridLayout_4.addWidget(self.list_mass_selected, 0, 2, 6, 1)
        self.list_mass_unselect = QtWidgets.QListWidget(self.gbox_MultiSelect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_mass_unselect.sizePolicy().hasHeightForWidth())
        self.list_mass_unselect.setSizePolicy(sizePolicy)
        self.list_mass_unselect.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_mass_unselect.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.list_mass_unselect.setObjectName("list_mass_unselect")
        item = QtWidgets.QListWidgetItem()
        self.list_mass_unselect.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_mass_unselect.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_mass_unselect.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_mass_unselect.addItem(item)
        self.gridLayout_4.addWidget(self.list_mass_unselect, 0, 0, 6, 1)
        self.btn_mass_add = QtWidgets.QToolButton(self.gbox_MultiSelect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_mass_add.sizePolicy().hasHeightForWidth())
        self.btn_mass_add.setSizePolicy(sizePolicy)
        self.btn_mass_add.setObjectName("btn_mass_add")
        self.gridLayout_4.addWidget(self.btn_mass_add, 1, 1, 2, 1)
        self.btn_mass_del = QtWidgets.QToolButton(self.gbox_MultiSelect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_mass_del.sizePolicy().hasHeightForWidth())
        self.btn_mass_del.setSizePolicy(sizePolicy)
        self.btn_mass_del.setObjectName("btn_mass_del")
        self.gridLayout_4.addWidget(self.btn_mass_del, 3, 1, 2, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_4)
        self.horizontalLayout_4.addWidget(self.gbox_MultiSelect)
        self.verticalLayout.addWidget(self.frame_mass)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.tab_box.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 70, 511, 138))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_data_1 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_data_1.setFont(font)
        self.lbl_data_1.setObjectName("lbl_data_1")
        self.gridLayout.addWidget(self.lbl_data_1, 0, 0, 1, 1)
        self.ledt_data_1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.ledt_data_1.setReadOnly(True)
        self.ledt_data_1.setObjectName("ledt_data_1")
        self.gridLayout.addWidget(self.ledt_data_1, 0, 1, 1, 1)
        self.lbl_data_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_data_2.setFont(font)
        self.lbl_data_2.setObjectName("lbl_data_2")
        self.gridLayout.addWidget(self.lbl_data_2, 1, 0, 1, 1)
        self.ledt_data_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.ledt_data_2.setReadOnly(True)
        self.ledt_data_2.setObjectName("ledt_data_2")
        self.gridLayout.addWidget(self.ledt_data_2, 1, 1, 1, 1)
        self.btn_data_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_data_2.setObjectName("btn_data_2")
        self.gridLayout.addWidget(self.btn_data_2, 1, 2, 1, 1)
        self.lbl_data_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_data_3.setFont(font)
        self.lbl_data_3.setObjectName("lbl_data_3")
        self.gridLayout.addWidget(self.lbl_data_3, 2, 0, 1, 1)
        self.ledt_data_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.ledt_data_3.setReadOnly(True)
        self.ledt_data_3.setObjectName("ledt_data_3")
        self.gridLayout.addWidget(self.ledt_data_3, 2, 1, 1, 1)
        self.btn_data_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_data_3.setObjectName("btn_data_3")
        self.gridLayout.addWidget(self.btn_data_3, 2, 2, 1, 1)
        self.lbl_data_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_data_4.setFont(font)
        self.lbl_data_4.setObjectName("lbl_data_4")
        self.gridLayout.addWidget(self.lbl_data_4, 3, 0, 1, 1)
        self.ledt_data_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.ledt_data_4.setReadOnly(True)
        self.ledt_data_4.setObjectName("ledt_data_4")
        self.gridLayout.addWidget(self.ledt_data_4, 3, 1, 1, 1)
        self.btn_data_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_data_4.setObjectName("btn_data_4")
        self.gridLayout.addWidget(self.btn_data_4, 3, 2, 1, 1)
        self.lbl_data_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_data_5.setFont(font)
        self.lbl_data_5.setObjectName("lbl_data_5")
        self.gridLayout.addWidget(self.lbl_data_5, 4, 0, 1, 1)
        self.ledt_data_5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.ledt_data_5.setReadOnly(True)
        self.ledt_data_5.setObjectName("ledt_data_5")
        self.gridLayout.addWidget(self.ledt_data_5, 4, 1, 1, 1)
        self.btn_data_5 = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_data_5.setObjectName("btn_data_5")
        self.gridLayout.addWidget(self.btn_data_5, 4, 2, 1, 1)
        self.tab_box.addTab(self.tab_2, "")
        self.tab_summary = QtWidgets.QWidget()
        self.tab_summary.setObjectName("tab_summary")
        self.tab_box.addTab(self.tab_summary, "")
        self.verticalLayout_2.addWidget(self.tab_box)
        self.layout_status = QtWidgets.QHBoxLayout()
        self.layout_status.setObjectName("layout_status")
        self.lbl_status = QtWidgets.QLabel(self.centralwidget)
        self.lbl_status.setObjectName("lbl_status")
        self.layout_status.addWidget(self.lbl_status)
        self.pbar_status = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbar_status.sizePolicy().hasHeightForWidth())
        self.pbar_status.setSizePolicy(sizePolicy)
        self.pbar_status.setBaseSize(QtCore.QSize(0, 0))
        self.pbar_status.setProperty("value", 0)
        self.pbar_status.setTextVisible(False)
        self.pbar_status.setInvertedAppearance(False)
        self.pbar_status.setObjectName("pbar_status")
        self.layout_status.addWidget(self.pbar_status)
        self.verticalLayout_2.addLayout(self.layout_status)
        IndexWindow.setCentralWidget(self.centralwidget)
        self.action = QtWidgets.QAction(IndexWindow)
        self.action.setObjectName("action")

        self.retranslateUi(IndexWindow)
        self.tab_box.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(IndexWindow)

    def retranslateUi(self, IndexWindow):
        _translate = QtCore.QCoreApplication.translate
        IndexWindow.setWindowTitle(_translate("IndexWindow", "AutoConfiguration(已授权)"))
        self.btn_get_license.setToolTip(_translate("IndexWindow", "免费申请，请放心使用"))
        self.btn_get_license.setText(_translate("IndexWindow", "联网申请授权"))
        self.btn_import.setText(_translate("IndexWindow", "Import"))
        self.btn_export.setText(_translate("IndexWindow", "Export"))
        self.btn_cfg_data.setText(_translate("IndexWindow", "Data"))
        self.lbl_data_TM.setText(_translate("IndexWindow", "TYPE_MS2"))
        self.lbl_data_PM.setText(_translate("IndexWindow", "PATH_MS2"))
        self.btn_data_PM.setText(_translate("IndexWindow", "浏览"))
        self.lbl_data_PF.setText(_translate("IndexWindow", "PATH_FASTA"))
        self.btn_data_PF.setText(_translate("IndexWindow", "浏览"))
        self.lbl_data_PFE.setText(_translate("IndexWindow", "PATH_FASTA_EXPORT"))
        self.btn_data_PFE.setText(_translate("IndexWindow", "浏览"))
        self.lbl_data_PRE.setText(_translate("IndexWindow", "PATH_RESULT_EXPORT"))
        self.btn_data_PRE.setText(_translate("IndexWindow", "浏览"))
        self.btn_cfg_biology.setText(_translate("IndexWindow", "Biology"))
        self.cbox_bio_TD.setItemText(0, _translate("IndexWindow", "0"))
        self.cbox_bio_TD.setItemText(1, _translate("IndexWindow", "1"))
        self.cbox_bio_TD.setItemText(2, _translate("IndexWindow", "2"))
        self.lbl_bio_PT.setText(_translate("IndexWindow", "PATH_TEMP"))
        self.lbl_bio_TD.setText(_translate("IndexWindow", "TYPE_DIGEST"))
        self.lbl_bio_NE.setText(_translate("IndexWindow", "NAME_ENZYME"))
        self.btn_bio_PT.setText(_translate("IndexWindow", "浏览"))
        self.btn_cfg_mass.setText(_translate("IndexWindow", "Mass"))
        self.gbox_MultiSelect.setTitle(_translate("IndexWindow", "去冗余多选框"))
        __sortingEnabled = self.list_mass_selected.isSortingEnabled()
        self.list_mass_selected.setSortingEnabled(False)
        item = self.list_mass_selected.item(0)
        item.setText(_translate("IndexWindow", "项目3"))
        self.list_mass_selected.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.list_mass_unselect.isSortingEnabled()
        self.list_mass_unselect.setSortingEnabled(False)
        item = self.list_mass_unselect.item(0)
        item.setText(_translate("IndexWindow", "项目1"))
        item = self.list_mass_unselect.item(1)
        item.setText(_translate("IndexWindow", "项目2"))
        item = self.list_mass_unselect.item(2)
        item.setText(_translate("IndexWindow", "项目4"))
        item = self.list_mass_unselect.item(3)
        item.setText(_translate("IndexWindow", "项目5"))
        self.list_mass_unselect.setSortingEnabled(__sortingEnabled)
        self.btn_mass_add.setText(_translate("IndexWindow", "->"))
        self.btn_mass_del.setText(_translate("IndexWindow", "<-"))
        self.tab_box.setTabText(self.tab_box.indexOf(self.tab_1), _translate("IndexWindow", "ConfigOne"))
        self.lbl_data_1.setText(_translate("IndexWindow", "TYPE_MS2"))
        self.lbl_data_2.setText(_translate("IndexWindow", "PATH_MS2"))
        self.btn_data_2.setText(_translate("IndexWindow", "浏览"))
        self.lbl_data_3.setText(_translate("IndexWindow", "PATH_MS2"))
        self.btn_data_3.setText(_translate("IndexWindow", "浏览"))
        self.lbl_data_4.setText(_translate("IndexWindow", "PATH_FASTA_EXPORT"))
        self.btn_data_4.setText(_translate("IndexWindow", "浏览"))
        self.lbl_data_5.setText(_translate("IndexWindow", "PATH_RESULT_EXPORT"))
        self.btn_data_5.setText(_translate("IndexWindow", "浏览"))
        self.tab_box.setTabText(self.tab_box.indexOf(self.tab_2), _translate("IndexWindow", "ConfigTwo"))
        self.tab_box.setTabText(self.tab_box.indexOf(self.tab_summary), _translate("IndexWindow", "Summary"))
        self.lbl_status.setText(_translate("IndexWindow", "运行状态"))
        self.pbar_status.setFormat(_translate("IndexWindow", "%p%"))
        self.action.setText(_translate("IndexWindow", "软件注册"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IndexWindow = QtWidgets.QMainWindow()
    ui = Ui_IndexWindow()
    ui.setupUi(IndexWindow)
    IndexWindow.show()
    sys.exit(app.exec_())
