# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Polly\Eric_Workspace\AutoConfigGUI\IndexWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IndexWindow(object):
    def setupUi(self, IndexWindow):
        IndexWindow.setObjectName("IndexWindow")
        IndexWindow.setEnabled(True)
        IndexWindow.resize(846, 614)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(IndexWindow.sizePolicy().hasHeightForWidth())
        IndexWindow.setSizePolicy(sizePolicy)
        IndexWindow.setTabletTracking(False)
        IndexWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(IndexWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout_menu = QtWidgets.QHBoxLayout()
        self.layout_menu.setObjectName("layout_menu")
        self.btn_get_license = QtWidgets.QPushButton(self.centralwidget)
        self.btn_get_license.setAutoFillBackground(True)
        self.btn_get_license.setStyleSheet("color: rgb(0, 0, 255);")
        self.btn_get_license.setAutoDefault(False)
        self.btn_get_license.setDefault(False)
        self.btn_get_license.setFlat(True)
        self.btn_get_license.setObjectName("btn_get_license")
        self.layout_menu.addWidget(self.btn_get_license)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_menu.addItem(spacerItem)
        self.btn_import = QtWidgets.QPushButton(self.centralwidget)
        self.btn_import.setObjectName("btn_import")
        self.layout_menu.addWidget(self.btn_import)
        self.btn_export = QtWidgets.QPushButton(self.centralwidget)
        self.btn_export.setObjectName("btn_export")
        self.layout_menu.addWidget(self.btn_export)
        self.verticalLayout_2.addLayout(self.layout_menu)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.tab_box = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_box.setEnabled(True)
        self.tab_box.setTabletTracking(False)
        self.tab_box.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_box.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_box.setIconSize(QtCore.QSize(16, 16))
        self.tab_box.setElideMode(QtCore.Qt.ElideNone)
        self.tab_box.setUsesScrollButtons(True)
        self.tab_box.setDocumentMode(False)
        self.tab_box.setTabsClosable(False)
        self.tab_box.setMovable(False)
        self.tab_box.setTabBarAutoHide(False)
        self.tab_box.setObjectName("tab_box")
        self.tab_common = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_common.sizePolicy().hasHeightForWidth())
        self.tab_common.setSizePolicy(sizePolicy)
        self.tab_common.setObjectName("tab_common")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_common)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_common)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 822, 256))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_common_PRE = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_common_PRE.setFont(font)
        self.lbl_common_PRE.setObjectName("lbl_common_PRE")
        self.gridLayout.addWidget(self.lbl_common_PRE, 5, 0, 1, 1)
        self.list_common_PM = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_common_PM.sizePolicy().hasHeightForWidth())
        self.list_common_PM.setSizePolicy(sizePolicy)
        self.list_common_PM.setMinimumSize(QtCore.QSize(0, 150))
        self.list_common_PM.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.list_common_PM.setObjectName("list_common_PM")
        self.gridLayout.addWidget(self.list_common_PM, 1, 2, 3, 1)
        self.lbl_common_PF = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_common_PF.setFont(font)
        self.lbl_common_PF.setObjectName("lbl_common_PF")
        self.gridLayout.addWidget(self.lbl_common_PF, 4, 0, 1, 1)
        self.ledt_common_PF = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.ledt_common_PF.setReadOnly(True)
        self.ledt_common_PF.setObjectName("ledt_common_PF")
        self.gridLayout.addWidget(self.ledt_common_PF, 4, 2, 1, 1)
        self.cbox_common_TM = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_common_TM.sizePolicy().hasHeightForWidth())
        self.cbox_common_TM.setSizePolicy(sizePolicy)
        self.cbox_common_TM.setMinimumSize(QtCore.QSize(150, 0))
        self.cbox_common_TM.setObjectName("cbox_common_TM")
        self.cbox_common_TM.addItem("")
        self.cbox_common_TM.addItem("")
        self.cbox_common_TM.addItem("")
        self.gridLayout.addWidget(self.cbox_common_TM, 0, 2, 1, 2)
        self.btn_common_PM_clear = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_common_PM_clear.sizePolicy().hasHeightForWidth())
        self.btn_common_PM_clear.setSizePolicy(sizePolicy)
        self.btn_common_PM_clear.setSizeIncrement(QtCore.QSize(0, 1))
        self.btn_common_PM_clear.setObjectName("btn_common_PM_clear")
        self.gridLayout.addWidget(self.btn_common_PM_clear, 3, 3, 1, 1)
        self.lbl_common_PM = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_common_PM.setFont(font)
        self.lbl_common_PM.setObjectName("lbl_common_PM")
        self.gridLayout.addWidget(self.lbl_common_PM, 2, 0, 1, 1)
        self.ledt_common_PRE = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.ledt_common_PRE.setReadOnly(True)
        self.ledt_common_PRE.setObjectName("ledt_common_PRE")
        self.gridLayout.addWidget(self.ledt_common_PRE, 5, 2, 1, 1)
        self.btn_common_PRE = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.btn_common_PRE.setObjectName("btn_common_PRE")
        self.gridLayout.addWidget(self.btn_common_PRE, 5, 3, 1, 1)
        self.btn_common_PF = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.btn_common_PF.setObjectName("btn_common_PF")
        self.gridLayout.addWidget(self.btn_common_PF, 4, 3, 1, 1)
        self.btn_common_PM_add = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_common_PM_add.sizePolicy().hasHeightForWidth())
        self.btn_common_PM_add.setSizePolicy(sizePolicy)
        self.btn_common_PM_add.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_common_PM_add.setSizeIncrement(QtCore.QSize(0, 1))
        self.btn_common_PM_add.setObjectName("btn_common_PM_add")
        self.gridLayout.addWidget(self.btn_common_PM_add, 1, 3, 1, 1)
        self.lbl_common_TM = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_common_TM.setFont(font)
        self.lbl_common_TM.setObjectName("lbl_common_TM")
        self.gridLayout.addWidget(self.lbl_common_TM, 0, 0, 1, 1)
        self.btn_common_PM_del = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_common_PM_del.sizePolicy().hasHeightForWidth())
        self.btn_common_PM_del.setSizePolicy(sizePolicy)
        self.btn_common_PM_del.setSizeIncrement(QtCore.QSize(0, 1))
        self.btn_common_PM_del.setObjectName("btn_common_PM_del")
        self.gridLayout.addWidget(self.btn_common_PM_del, 2, 3, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.tab_box.addTab(self.tab_common, "")
        self.tab_config_1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_config_1.sizePolicy().hasHeightForWidth())
        self.tab_config_1.setSizePolicy(sizePolicy)
        self.tab_config_1.setObjectName("tab_config_1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_config_1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_config_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 805, 738))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_cfg_group_1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cfg_group_1.sizePolicy().hasHeightForWidth())
        self.btn_cfg_group_1.setSizePolicy(sizePolicy)
        self.btn_cfg_group_1.setMinimumSize(QtCore.QSize(0, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.btn_cfg_group_1.setFont(font)
        self.btn_cfg_group_1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_cfg_group_1.setAutoFillBackground(False)
        self.btn_cfg_group_1.setStyleSheet("QPushButton{text-align:left; border:none;margin-bottom:2px;}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon_show.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/icon_hide.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_cfg_group_1.setIcon(icon)
        self.btn_cfg_group_1.setCheckable(True)
        self.btn_cfg_group_1.setAutoDefault(False)
        self.btn_cfg_group_1.setDefault(False)
        self.btn_cfg_group_1.setFlat(False)
        self.btn_cfg_group_1.setObjectName("btn_cfg_group_1")
        self.verticalLayout.addWidget(self.btn_cfg_group_1)
        self.frame_group_1 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_group_1.sizePolicy().hasHeightForWidth())
        self.frame_group_1.setSizePolicy(sizePolicy)
        self.frame_group_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_group_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_group_1.setObjectName("frame_group_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_group_1)
        self.horizontalLayout_2.setContentsMargins(10, 2, 0, 8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.layout_data = QtWidgets.QGridLayout()
        self.layout_data.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_data.setObjectName("layout_data")
        self.cbox_cfg1_NMMC = QtWidgets.QComboBox(self.frame_group_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_cfg1_NMMC.sizePolicy().hasHeightForWidth())
        self.cbox_cfg1_NMMC.setSizePolicy(sizePolicy)
        self.cbox_cfg1_NMMC.setMinimumSize(QtCore.QSize(150, 0))
        self.cbox_cfg1_NMMC.setObjectName("cbox_cfg1_NMMC")
        self.cbox_cfg1_NMMC.addItem("")
        self.cbox_cfg1_NMMC.addItem("")
        self.cbox_cfg1_NMMC.addItem("")
        self.cbox_cfg1_NMMC.addItem("")
        self.layout_data.addWidget(self.cbox_cfg1_NMMC, 1, 1, 1, 1)
        self.lbl_cfg1_NMMC = QtWidgets.QLabel(self.frame_group_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_cfg1_NMMC.sizePolicy().hasHeightForWidth())
        self.lbl_cfg1_NMMC.setSizePolicy(sizePolicy)
        self.lbl_cfg1_NMMC.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg1_NMMC.setFont(font)
        self.lbl_cfg1_NMMC.setObjectName("lbl_cfg1_NMMC")
        self.layout_data.addWidget(self.lbl_cfg1_NMMC, 1, 0, 1, 1)
        self.lbl_cfg1_TD = QtWidgets.QLabel(self.frame_group_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_cfg1_TD.sizePolicy().hasHeightForWidth())
        self.lbl_cfg1_TD.setSizePolicy(sizePolicy)
        self.lbl_cfg1_TD.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg1_TD.setFont(font)
        self.lbl_cfg1_TD.setObjectName("lbl_cfg1_TD")
        self.layout_data.addWidget(self.lbl_cfg1_TD, 2, 0, 1, 1)
        self.lbl_cfg1_NE = QtWidgets.QLabel(self.frame_group_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_cfg1_NE.sizePolicy().hasHeightForWidth())
        self.lbl_cfg1_NE.setSizePolicy(sizePolicy)
        self.lbl_cfg1_NE.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg1_NE.setFont(font)
        self.lbl_cfg1_NE.setObjectName("lbl_cfg1_NE")
        self.layout_data.addWidget(self.lbl_cfg1_NE, 0, 0, 1, 1)
        self.lbl_cfg1_NMM = QtWidgets.QLabel(self.frame_group_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_cfg1_NMM.sizePolicy().hasHeightForWidth())
        self.lbl_cfg1_NMM.setSizePolicy(sizePolicy)
        self.lbl_cfg1_NMM.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg1_NMM.setFont(font)
        self.lbl_cfg1_NMM.setObjectName("lbl_cfg1_NMM")
        self.layout_data.addWidget(self.lbl_cfg1_NMM, 4, 0, 1, 1)
        self.cbox_cfg1_NE = QtWidgets.QComboBox(self.frame_group_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_cfg1_NE.sizePolicy().hasHeightForWidth())
        self.cbox_cfg1_NE.setSizePolicy(sizePolicy)
        self.cbox_cfg1_NE.setMinimumSize(QtCore.QSize(150, 0))
        self.cbox_cfg1_NE.setObjectName("cbox_cfg1_NE")
        self.cbox_cfg1_NE.addItem("")
        self.layout_data.addWidget(self.cbox_cfg1_NE, 0, 1, 1, 1)
        self.cbox_cfg1_TD = QtWidgets.QComboBox(self.frame_group_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_cfg1_TD.sizePolicy().hasHeightForWidth())
        self.cbox_cfg1_TD.setSizePolicy(sizePolicy)
        self.cbox_cfg1_TD.setMinimumSize(QtCore.QSize(150, 0))
        self.cbox_cfg1_TD.setObjectName("cbox_cfg1_TD")
        self.cbox_cfg1_TD.addItem("")
        self.cbox_cfg1_TD.addItem("")
        self.cbox_cfg1_TD.addItem("")
        self.layout_data.addWidget(self.cbox_cfg1_TD, 2, 1, 1, 1)
        self.cbox_cfg1_NMM = QtWidgets.QComboBox(self.frame_group_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_cfg1_NMM.sizePolicy().hasHeightForWidth())
        self.cbox_cfg1_NMM.setSizePolicy(sizePolicy)
        self.cbox_cfg1_NMM.setMinimumSize(QtCore.QSize(150, 0))
        self.cbox_cfg1_NMM.setObjectName("cbox_cfg1_NMM")
        self.cbox_cfg1_NMM.addItem("")
        self.cbox_cfg1_NMM.addItem("")
        self.cbox_cfg1_NMM.addItem("")
        self.cbox_cfg1_NMM.addItem("")
        self.layout_data.addWidget(self.cbox_cfg1_NMM, 4, 1, 1, 1)
        self.gbox_MultiSelect_2 = QtWidgets.QFrame(self.frame_group_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbox_MultiSelect_2.sizePolicy().hasHeightForWidth())
        self.gbox_MultiSelect_2.setSizePolicy(sizePolicy)
        self.gbox_MultiSelect_2.setMinimumSize(QtCore.QSize(0, 250))
        self.gbox_MultiSelect_2.setObjectName("gbox_MultiSelect_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.gbox_MultiSelect_2)
        self.horizontalLayout_7.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbl_cfg1_NM = QtWidgets.QLabel(self.gbox_MultiSelect_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_cfg1_NM.sizePolicy().hasHeightForWidth())
        self.lbl_cfg1_NM.setSizePolicy(sizePolicy)
        self.lbl_cfg1_NM.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg1_NM.setFont(font)
        self.lbl_cfg1_NM.setObjectName("lbl_cfg1_NM")
        self.horizontalLayout_7.addWidget(self.lbl_cfg1_NM)
        self.splitter_3 = QtWidgets.QSplitter(self.gbox_MultiSelect_2)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.label_3 = QtWidgets.QLabel(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.splitter_3)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.list_cfg1_NMF = QtWidgets.QListWidget(self.gbox_MultiSelect_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_cfg1_NMF.sizePolicy().hasHeightForWidth())
        self.list_cfg1_NMF.setSizePolicy(sizePolicy)
        self.list_cfg1_NMF.setMinimumSize(QtCore.QSize(0, 100))
        self.list_cfg1_NMF.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_cfg1_NMF.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.list_cfg1_NMF.setObjectName("list_cfg1_NMF")
        item = QtWidgets.QListWidgetItem()
        self.list_cfg1_NMF.addItem(item)
        self.verticalLayout_9.addWidget(self.list_cfg1_NMF)
        self.list_cfg1_NMV = QtWidgets.QListWidget(self.gbox_MultiSelect_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_cfg1_NMV.sizePolicy().hasHeightForWidth())
        self.list_cfg1_NMV.setSizePolicy(sizePolicy)
        self.list_cfg1_NMV.setMinimumSize(QtCore.QSize(0, 100))
        self.list_cfg1_NMV.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_cfg1_NMV.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.list_cfg1_NMV.setObjectName("list_cfg1_NMV")
        item = QtWidgets.QListWidgetItem()
        self.list_cfg1_NMV.addItem(item)
        self.verticalLayout_9.addWidget(self.list_cfg1_NMV)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.splitter_5 = QtWidgets.QSplitter(self.gbox_MultiSelect_2)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.layoutWidget_2 = QtWidgets.QWidget(self.splitter_5)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.btn_cfg1_f2u = QtWidgets.QToolButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cfg1_f2u.sizePolicy().hasHeightForWidth())
        self.btn_cfg1_f2u.setSizePolicy(sizePolicy)
        self.btn_cfg1_f2u.setObjectName("btn_cfg1_f2u")
        self.verticalLayout_10.addWidget(self.btn_cfg1_f2u)
        self.btn_cfg1_u2f = QtWidgets.QToolButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cfg1_u2f.sizePolicy().hasHeightForWidth())
        self.btn_cfg1_u2f.setSizePolicy(sizePolicy)
        self.btn_cfg1_u2f.setObjectName("btn_cfg1_u2f")
        self.verticalLayout_10.addWidget(self.btn_cfg1_u2f)
        self.layoutWidget_3 = QtWidgets.QWidget(self.splitter_5)
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.btn_mass_v2u_2 = QtWidgets.QToolButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_mass_v2u_2.sizePolicy().hasHeightForWidth())
        self.btn_mass_v2u_2.setSizePolicy(sizePolicy)
        self.btn_mass_v2u_2.setObjectName("btn_mass_v2u_2")
        self.verticalLayout_11.addWidget(self.btn_mass_v2u_2)
        self.btn_cfg1_u2v = QtWidgets.QToolButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cfg1_u2v.sizePolicy().hasHeightForWidth())
        self.btn_cfg1_u2v.setSizePolicy(sizePolicy)
        self.btn_cfg1_u2v.setObjectName("btn_cfg1_u2v")
        self.verticalLayout_11.addWidget(self.btn_cfg1_u2v)
        self.horizontalLayout_7.addWidget(self.splitter_5)
        self.list_cfg1_NM = QtWidgets.QListWidget(self.gbox_MultiSelect_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_cfg1_NM.sizePolicy().hasHeightForWidth())
        self.list_cfg1_NM.setSizePolicy(sizePolicy)
        self.list_cfg1_NM.setMinimumSize(QtCore.QSize(0, 180))
        self.list_cfg1_NM.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_cfg1_NM.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.list_cfg1_NM.setObjectName("list_cfg1_NM")
        item = QtWidgets.QListWidgetItem()
        self.list_cfg1_NM.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_cfg1_NM.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_cfg1_NM.addItem(item)
        self.horizontalLayout_7.addWidget(self.list_cfg1_NM)
        self.layout_data.addWidget(self.gbox_MultiSelect_2, 3, 0, 1, 3)
        self.horizontalLayout_2.addLayout(self.layout_data)
        self.verticalLayout.addWidget(self.frame_group_1)
        self.btn_cfg_group_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cfg_group_2.sizePolicy().hasHeightForWidth())
        self.btn_cfg_group_2.setSizePolicy(sizePolicy)
        self.btn_cfg_group_2.setMinimumSize(QtCore.QSize(0, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.btn_cfg_group_2.setFont(font)
        self.btn_cfg_group_2.setStyleSheet("QPushButton{text-align:left; border:none;margin-bottom:2px;}")
        self.btn_cfg_group_2.setIcon(icon)
        self.btn_cfg_group_2.setCheckable(True)
        self.btn_cfg_group_2.setFlat(False)
        self.btn_cfg_group_2.setObjectName("btn_cfg_group_2")
        self.verticalLayout.addWidget(self.btn_cfg_group_2)
        self.frame_group_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_group_2.sizePolicy().hasHeightForWidth())
        self.frame_group_2.setSizePolicy(sizePolicy)
        self.frame_group_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_group_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_group_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_group_2.setObjectName("frame_group_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_group_2)
        self.horizontalLayout_3.setContentsMargins(10, 2, 0, 8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbl_cfg1_US = QtWidgets.QLabel(self.frame_group_2)
        self.lbl_cfg1_US.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg1_US.setFont(font)
        self.lbl_cfg1_US.setObjectName("lbl_cfg1_US")
        self.gridLayout_3.addWidget(self.lbl_cfg1_US, 0, 0, 1, 1)
        self.ledt_cfg1_UA = QtWidgets.QLineEdit(self.frame_group_2)
        self.ledt_cfg1_UA.setReadOnly(False)
        self.ledt_cfg1_UA.setObjectName("ledt_cfg1_UA")
        self.gridLayout_3.addWidget(self.ledt_cfg1_UA, 1, 1, 1, 1)
        self.lbl_cfg1_UC = QtWidgets.QLabel(self.frame_group_2)
        self.lbl_cfg1_UC.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg1_UC.setFont(font)
        self.lbl_cfg1_UC.setObjectName("lbl_cfg1_UC")
        self.gridLayout_3.addWidget(self.lbl_cfg1_UC, 4, 0, 1, 1)
        self.lbl_cfg1_UA = QtWidgets.QLabel(self.frame_group_2)
        self.lbl_cfg1_UA.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg1_UA.setFont(font)
        self.lbl_cfg1_UA.setObjectName("lbl_cfg1_UA")
        self.gridLayout_3.addWidget(self.lbl_cfg1_UA, 1, 0, 1, 1)
        self.ledt_cfg1_ULA = QtWidgets.QLineEdit(self.frame_group_2)
        self.ledt_cfg1_ULA.setReadOnly(False)
        self.ledt_cfg1_ULA.setObjectName("ledt_cfg1_ULA")
        self.gridLayout_3.addWidget(self.ledt_cfg1_ULA, 5, 1, 1, 1)
        self.lbl_cfg1_ULL = QtWidgets.QLabel(self.frame_group_2)
        self.lbl_cfg1_ULL.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg1_ULL.setFont(font)
        self.lbl_cfg1_ULL.setObjectName("lbl_cfg1_ULL")
        self.gridLayout_3.addWidget(self.lbl_cfg1_ULL, 2, 0, 1, 1)
        self.lbl_cfg1_ULA = QtWidgets.QLabel(self.frame_group_2)
        self.lbl_cfg1_ULA.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg1_ULA.setFont(font)
        self.lbl_cfg1_ULA.setObjectName("lbl_cfg1_ULA")
        self.gridLayout_3.addWidget(self.lbl_cfg1_ULA, 5, 0, 1, 1)
        self.ledt_cfg1_US = QtWidgets.QLineEdit(self.frame_group_2)
        self.ledt_cfg1_US.setReadOnly(False)
        self.ledt_cfg1_US.setObjectName("ledt_cfg1_US")
        self.gridLayout_3.addWidget(self.ledt_cfg1_US, 0, 1, 1, 1)
        self.ledt_cfg1_ULL = QtWidgets.QLineEdit(self.frame_group_2)
        self.ledt_cfg1_ULL.setReadOnly(False)
        self.ledt_cfg1_ULL.setObjectName("ledt_cfg1_ULL")
        self.gridLayout_3.addWidget(self.ledt_cfg1_ULL, 2, 1, 1, 1)
        self.ledt_cfg1_UC = QtWidgets.QLineEdit(self.frame_group_2)
        self.ledt_cfg1_UC.setReadOnly(False)
        self.ledt_cfg1_UC.setObjectName("ledt_cfg1_UC")
        self.gridLayout_3.addWidget(self.ledt_cfg1_UC, 4, 1, 1, 1)
        self.lbl_cfg1_ULU = QtWidgets.QLabel(self.frame_group_2)
        self.lbl_cfg1_ULU.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg1_ULU.setFont(font)
        self.lbl_cfg1_ULU.setObjectName("lbl_cfg1_ULU")
        self.gridLayout_3.addWidget(self.lbl_cfg1_ULU, 3, 0, 1, 1)
        self.ledt_cfg1_ULU = QtWidgets.QLineEdit(self.frame_group_2)
        self.ledt_cfg1_ULU.setReadOnly(False)
        self.ledt_cfg1_ULU.setObjectName("ledt_cfg1_ULU")
        self.gridLayout_3.addWidget(self.ledt_cfg1_ULU, 3, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        self.verticalLayout.addWidget(self.frame_group_2)
        self.btn_cfg_group_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cfg_group_3.sizePolicy().hasHeightForWidth())
        self.btn_cfg_group_3.setSizePolicy(sizePolicy)
        self.btn_cfg_group_3.setMinimumSize(QtCore.QSize(0, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.btn_cfg_group_3.setFont(font)
        self.btn_cfg_group_3.setStyleSheet("QPushButton{text-align:left; border:none;margin-bottom:2px;}")
        self.btn_cfg_group_3.setIcon(icon)
        self.btn_cfg_group_3.setCheckable(True)
        self.btn_cfg_group_3.setFlat(False)
        self.btn_cfg_group_3.setObjectName("btn_cfg_group_3")
        self.verticalLayout.addWidget(self.btn_cfg_group_3)
        self.frame_group_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_group_3.sizePolicy().hasHeightForWidth())
        self.frame_group_3.setSizePolicy(sizePolicy)
        self.frame_group_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_group_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_group_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_group_3.setObjectName("frame_group_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_group_3)
        self.horizontalLayout_8.setContentsMargins(10, 2, 0, 8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.ledt_cfg1_PTF = QtWidgets.QLineEdit(self.frame_group_3)
        self.ledt_cfg1_PTF.setReadOnly(False)
        self.ledt_cfg1_PTF.setObjectName("ledt_cfg1_PTF")
        self.gridLayout_6.addWidget(self.ledt_cfg1_PTF, 1, 1, 1, 1)
        self.lbl_cfg1_FP = QtWidgets.QLabel(self.frame_group_3)
        self.lbl_cfg1_FP.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg1_FP.setFont(font)
        self.lbl_cfg1_FP.setObjectName("lbl_cfg1_FP")
        self.gridLayout_6.addWidget(self.lbl_cfg1_FP, 4, 0, 1, 1)
        self.lbl_cfg1_TA = QtWidgets.QLabel(self.frame_group_3)
        self.lbl_cfg1_TA.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg1_TA.setFont(font)
        self.lbl_cfg1_TA.setObjectName("lbl_cfg1_TA")
        self.gridLayout_6.addWidget(self.lbl_cfg1_TA, 2, 0, 1, 1)
        self.lbl_cfg1_NT = QtWidgets.QLabel(self.frame_group_3)
        self.lbl_cfg1_NT.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg1_NT.setFont(font)
        self.lbl_cfg1_NT.setObjectName("lbl_cfg1_NT")
        self.gridLayout_6.addWidget(self.lbl_cfg1_NT, 3, 0, 1, 1)
        self.lbl_cfg1_PTP = QtWidgets.QLabel(self.frame_group_3)
        self.lbl_cfg1_PTP.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg1_PTP.setFont(font)
        self.lbl_cfg1_PTP.setObjectName("lbl_cfg1_PTP")
        self.gridLayout_6.addWidget(self.lbl_cfg1_PTP, 0, 0, 1, 1)
        self.ledt_cfg1_PTP = QtWidgets.QLineEdit(self.frame_group_3)
        self.ledt_cfg1_PTP.setReadOnly(False)
        self.ledt_cfg1_PTP.setObjectName("ledt_cfg1_PTP")
        self.gridLayout_6.addWidget(self.ledt_cfg1_PTP, 0, 1, 1, 1)
        self.ledt_cfg1_FP = QtWidgets.QLineEdit(self.frame_group_3)
        self.ledt_cfg1_FP.setReadOnly(False)
        self.ledt_cfg1_FP.setObjectName("ledt_cfg1_FP")
        self.gridLayout_6.addWidget(self.ledt_cfg1_FP, 4, 1, 1, 1)
        self.lbl_cfg1_PTF = QtWidgets.QLabel(self.frame_group_3)
        self.lbl_cfg1_PTF.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_cfg1_PTF.setFont(font)
        self.lbl_cfg1_PTF.setObjectName("lbl_cfg1_PTF")
        self.gridLayout_6.addWidget(self.lbl_cfg1_PTF, 1, 0, 1, 1)
        self.cbox_cfg1_TA = QtWidgets.QComboBox(self.frame_group_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_cfg1_TA.sizePolicy().hasHeightForWidth())
        self.cbox_cfg1_TA.setSizePolicy(sizePolicy)
        self.cbox_cfg1_TA.setMinimumSize(QtCore.QSize(150, 0))
        self.cbox_cfg1_TA.setObjectName("cbox_cfg1_TA")
        self.cbox_cfg1_TA.addItem("")
        self.gridLayout_6.addWidget(self.cbox_cfg1_TA, 2, 1, 1, 1)
        self.cbox_cfg1_NT = QtWidgets.QComboBox(self.frame_group_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_cfg1_NT.sizePolicy().hasHeightForWidth())
        self.cbox_cfg1_NT.setSizePolicy(sizePolicy)
        self.cbox_cfg1_NT.setMinimumSize(QtCore.QSize(150, 0))
        self.cbox_cfg1_NT.setObjectName("cbox_cfg1_NT")
        self.cbox_cfg1_NT.addItem("")
        self.cbox_cfg1_NT.addItem("")
        self.cbox_cfg1_NT.addItem("")
        self.cbox_cfg1_NT.addItem("")
        self.cbox_cfg1_NT.addItem("")
        self.gridLayout_6.addWidget(self.cbox_cfg1_NT, 3, 1, 1, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout_6)
        self.verticalLayout.addWidget(self.frame_group_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.tab_box.addTab(self.tab_config_1, "")
        self.tab_summary = QtWidgets.QWidget()
        self.tab_summary.setObjectName("tab_summary")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_summary)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_summary)
        self.scrollArea_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 805, 503))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_summary_group_1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_summary_group_1.sizePolicy().hasHeightForWidth())
        self.btn_summary_group_1.setSizePolicy(sizePolicy)
        self.btn_summary_group_1.setMinimumSize(QtCore.QSize(0, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.btn_summary_group_1.setFont(font)
        self.btn_summary_group_1.setStyleSheet("QPushButton{text-align:left; border:none;margin-bottom:2px;}")
        self.btn_summary_group_1.setIcon(icon)
        self.btn_summary_group_1.setCheckable(True)
        self.btn_summary_group_1.setFlat(False)
        self.btn_summary_group_1.setObjectName("btn_summary_group_1")
        self.verticalLayout_5.addWidget(self.btn_summary_group_1)
        self.tableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setStyleSheet("QTableWidget{margin-left:20px;}")
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout_5.addWidget(self.tableWidget)
        self.btn_summary_group_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_summary_group_2.sizePolicy().hasHeightForWidth())
        self.btn_summary_group_2.setSizePolicy(sizePolicy)
        self.btn_summary_group_2.setMinimumSize(QtCore.QSize(0, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.btn_summary_group_2.setFont(font)
        self.btn_summary_group_2.setStyleSheet("QPushButton{text-align:left; border:none;margin-bottom:2px;}")
        self.btn_summary_group_2.setIcon(icon)
        self.btn_summary_group_2.setCheckable(True)
        self.btn_summary_group_2.setFlat(False)
        self.btn_summary_group_2.setObjectName("btn_summary_group_2")
        self.verticalLayout_5.addWidget(self.btn_summary_group_2)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_2.sizePolicy().hasHeightForWidth())
        self.tableWidget_2.setSizePolicy(sizePolicy)
        self.tableWidget_2.setStyleSheet("QTableWidget{margin-left:20px;}")
        self.tableWidget_2.setAlternatingRowColors(False)
        self.tableWidget_2.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_2.setWordWrap(True)
        self.tableWidget_2.setCornerButtonEnabled(True)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 1, item)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_2.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(25)
        self.verticalLayout_5.addWidget(self.tableWidget_2)
        self.btn_summary_group_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_summary_group_3.sizePolicy().hasHeightForWidth())
        self.btn_summary_group_3.setSizePolicy(sizePolicy)
        self.btn_summary_group_3.setMinimumSize(QtCore.QSize(0, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.btn_summary_group_3.setFont(font)
        self.btn_summary_group_3.setStyleSheet("QPushButton{text-align:left; border:none;margin-bottom:2px;}")
        self.btn_summary_group_3.setIcon(icon)
        self.btn_summary_group_3.setCheckable(True)
        self.btn_summary_group_3.setFlat(False)
        self.btn_summary_group_3.setObjectName("btn_summary_group_3")
        self.verticalLayout_5.addWidget(self.btn_summary_group_3)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_3.sizePolicy().hasHeightForWidth())
        self.tableWidget_3.setSizePolicy(sizePolicy)
        self.tableWidget_3.setStyleSheet("QTableWidget{margin-left:20px;}")
        self.tableWidget_3.setAlternatingRowColors(False)
        self.tableWidget_3.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget_3.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_3.setWordWrap(True)
        self.tableWidget_3.setCornerButtonEnabled(True)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 1, item)
        self.tableWidget_3.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget_3.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_3.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_3.verticalHeader().setVisible(False)
        self.tableWidget_3.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_3.verticalHeader().setDefaultSectionSize(25)
        self.verticalLayout_5.addWidget(self.tableWidget_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_4.addWidget(self.scrollArea_3)
        self.tab_box.addTab(self.tab_summary, "")
        self.verticalLayout_2.addWidget(self.tab_box)
        self.layout_status = QtWidgets.QHBoxLayout()
        self.layout_status.setObjectName("layout_status")
        self.lbl_status = QtWidgets.QLabel(self.centralwidget)
        self.lbl_status.setObjectName("lbl_status")
        self.layout_status.addWidget(self.lbl_status)
        self.pbar_status = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbar_status.sizePolicy().hasHeightForWidth())
        self.pbar_status.setSizePolicy(sizePolicy)
        self.pbar_status.setBaseSize(QtCore.QSize(0, 0))
        self.pbar_status.setProperty("value", 0)
        self.pbar_status.setTextVisible(False)
        self.pbar_status.setInvertedAppearance(False)
        self.pbar_status.setObjectName("pbar_status")
        self.layout_status.addWidget(self.pbar_status)
        self.verticalLayout_2.addLayout(self.layout_status)
        IndexWindow.setCentralWidget(self.centralwidget)
        self.action = QtWidgets.QAction(IndexWindow)
        self.action.setObjectName("action")

        self.retranslateUi(IndexWindow)
        self.tab_box.setCurrentIndex(1)
        self.btn_cfg_group_1.toggled['bool'].connect(self.frame_group_1.setHidden)
        self.btn_cfg_group_2.toggled['bool'].connect(self.frame_group_2.setHidden)
        self.btn_cfg_group_3.toggled['bool'].connect(self.frame_group_3.setHidden)
        QtCore.QMetaObject.connectSlotsByName(IndexWindow)

    def retranslateUi(self, IndexWindow):
        _translate = QtCore.QCoreApplication.translate
        IndexWindow.setWindowTitle(_translate("IndexWindow", "AutoConfiguration(已授权)"))
        self.btn_get_license.setToolTip(_translate("IndexWindow", "免费申请，请放心使用"))
        self.btn_get_license.setText(_translate("IndexWindow", "Register"))
        self.btn_import.setText(_translate("IndexWindow", "Import"))
        self.btn_export.setText(_translate("IndexWindow", "Export"))
        self.lbl_common_PRE.setText(_translate("IndexWindow", "PATH_RESULT_EXPORT"))
        self.lbl_common_PF.setText(_translate("IndexWindow", "PATH_FASTA"))
        self.cbox_common_TM.setItemText(0, _translate("IndexWindow", "raw"))
        self.cbox_common_TM.setItemText(1, _translate("IndexWindow", "ms1"))
        self.cbox_common_TM.setItemText(2, _translate("IndexWindow", "mgf"))
        self.btn_common_PM_clear.setText(_translate("IndexWindow", "Clear"))
        self.lbl_common_PM.setText(_translate("IndexWindow", "PATH_MS2"))
        self.btn_common_PRE.setText(_translate("IndexWindow", "Browser"))
        self.btn_common_PF.setText(_translate("IndexWindow", "Browser"))
        self.btn_common_PM_add.setText(_translate("IndexWindow", "Add"))
        self.lbl_common_TM.setText(_translate("IndexWindow", "TYPE_MS2"))
        self.btn_common_PM_del.setText(_translate("IndexWindow", "Del"))
        self.tab_box.setTabText(self.tab_box.indexOf(self.tab_common), _translate("IndexWindow", "ConfigCommon"))
        self.btn_cfg_group_1.setText(_translate("IndexWindow", "Group 1"))
        self.cbox_cfg1_NMMC.setItemText(0, _translate("IndexWindow", "1"))
        self.cbox_cfg1_NMMC.setItemText(1, _translate("IndexWindow", "2"))
        self.cbox_cfg1_NMMC.setItemText(2, _translate("IndexWindow", "3"))
        self.cbox_cfg1_NMMC.setItemText(3, _translate("IndexWindow", "4"))
        self.lbl_cfg1_NMMC.setText(_translate("IndexWindow", "NUMBER_MAX_MISS_CLS"))
        self.lbl_cfg1_TD.setText(_translate("IndexWindow", "TYPE_DIGEST"))
        self.lbl_cfg1_NE.setText(_translate("IndexWindow", "NAME_ENZYME"))
        self.lbl_cfg1_NMM.setText(_translate("IndexWindow", "NUMBER_MAX_MOD"))
        self.cbox_cfg1_NE.setItemText(0, _translate("IndexWindow", "trpysin"))
        self.cbox_cfg1_TD.setItemText(0, _translate("IndexWindow", "specific"))
        self.cbox_cfg1_TD.setItemText(1, _translate("IndexWindow", "semi-specific"))
        self.cbox_cfg1_TD.setItemText(2, _translate("IndexWindow", "none-specific"))
        self.cbox_cfg1_NMM.setItemText(0, _translate("IndexWindow", "1"))
        self.cbox_cfg1_NMM.setItemText(1, _translate("IndexWindow", "2"))
        self.cbox_cfg1_NMM.setItemText(2, _translate("IndexWindow", "3"))
        self.cbox_cfg1_NMM.setItemText(3, _translate("IndexWindow", "4"))
        self.lbl_cfg1_NM.setText(_translate("IndexWindow", "NAME_MOD"))
        self.label_3.setText(_translate("IndexWindow", "Fixed"))
        self.label_4.setText(_translate("IndexWindow", "Variable"))
        __sortingEnabled = self.list_cfg1_NMF.isSortingEnabled()
        self.list_cfg1_NMF.setSortingEnabled(False)
        item = self.list_cfg1_NMF.item(0)
        item.setText(_translate("IndexWindow", "项目1"))
        self.list_cfg1_NMF.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.list_cfg1_NMV.isSortingEnabled()
        self.list_cfg1_NMV.setSortingEnabled(False)
        item = self.list_cfg1_NMV.item(0)
        item.setText(_translate("IndexWindow", "项目2"))
        self.list_cfg1_NMV.setSortingEnabled(__sortingEnabled)
        self.btn_cfg1_f2u.setText(_translate("IndexWindow", "->"))
        self.btn_cfg1_u2f.setText(_translate("IndexWindow", "<-"))
        self.btn_mass_v2u_2.setText(_translate("IndexWindow", "->"))
        self.btn_cfg1_u2v.setText(_translate("IndexWindow", "<-"))
        __sortingEnabled = self.list_cfg1_NM.isSortingEnabled()
        self.list_cfg1_NM.setSortingEnabled(False)
        item = self.list_cfg1_NM.item(0)
        item.setText(_translate("IndexWindow", "项目3"))
        item = self.list_cfg1_NM.item(1)
        item.setText(_translate("IndexWindow", "项目4"))
        item = self.list_cfg1_NM.item(2)
        item.setText(_translate("IndexWindow", "项目5"))
        self.list_cfg1_NM.setSortingEnabled(__sortingEnabled)
        self.btn_cfg_group_2.setText(_translate("IndexWindow", "Group 2"))
        self.lbl_cfg1_US.setText(_translate("IndexWindow", "UAA_SEQ"))
        self.lbl_cfg1_UC.setText(_translate("IndexWindow", "UAA_COM"))
        self.lbl_cfg1_UA.setText(_translate("IndexWindow", "UAA_AA"))
        self.lbl_cfg1_ULL.setText(_translate("IndexWindow", "UAA_LEN_LOW"))
        self.lbl_cfg1_ULA.setText(_translate("IndexWindow", "UAA_LINKED_AA"))
        self.lbl_cfg1_ULU.setText(_translate("IndexWindow", "UAA_LEN_UP"))
        self.btn_cfg_group_3.setText(_translate("IndexWindow", "Group 3"))
        self.lbl_cfg1_FP.setText(_translate("IndexWindow", "FDR_PSM"))
        self.lbl_cfg1_TA.setText(_translate("IndexWindow", "TYPE_ACTIVATION"))
        self.lbl_cfg1_NT.setText(_translate("IndexWindow", "NUMBER_THREAD"))
        self.lbl_cfg1_PTP.setText(_translate("IndexWindow", "PPM_TOL_PRECURSOR"))
        self.lbl_cfg1_PTF.setText(_translate("IndexWindow", "PPM_TOL_FRAGMENT"))
        self.cbox_cfg1_TA.setItemText(0, _translate("IndexWindow", "HCD"))
        self.cbox_cfg1_NT.setItemText(0, _translate("IndexWindow", "1"))
        self.cbox_cfg1_NT.setItemText(1, _translate("IndexWindow", "2"))
        self.cbox_cfg1_NT.setItemText(2, _translate("IndexWindow", "4"))
        self.cbox_cfg1_NT.setItemText(3, _translate("IndexWindow", "8"))
        self.cbox_cfg1_NT.setItemText(4, _translate("IndexWindow", "16"))
        self.tab_box.setTabText(self.tab_box.indexOf(self.tab_config_1), _translate("IndexWindow", "ConfigOne"))
        self.btn_summary_group_1.setText(_translate("IndexWindow", "Group 2"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("IndexWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("IndexWindow", "Property"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("IndexWindow", "Value"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("IndexWindow", "123"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("IndexWindow", "123"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.btn_summary_group_2.setText(_translate("IndexWindow", "Group 2"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("IndexWindow", "1"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("IndexWindow", "Property"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("IndexWindow", "Value"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("IndexWindow", "123"))
        item = self.tableWidget_2.item(0, 1)
        item.setText(_translate("IndexWindow", "123"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.btn_summary_group_3.setText(_translate("IndexWindow", "Group 2"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("IndexWindow", "1"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("IndexWindow", "Property"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("IndexWindow", "Value"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        item = self.tableWidget_3.item(0, 0)
        item.setText(_translate("IndexWindow", "123"))
        item = self.tableWidget_3.item(0, 1)
        item.setText(_translate("IndexWindow", "123"))
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("IndexWindow", "Save"))
        self.pushButton_3.setText(_translate("IndexWindow", "Run"))
        self.pushButton_2.setText(_translate("IndexWindow", "Stop"))
        self.tab_box.setTabText(self.tab_box.indexOf(self.tab_summary), _translate("IndexWindow", "Summary"))
        self.lbl_status.setText(_translate("IndexWindow", "运行状态"))
        self.pbar_status.setFormat(_translate("IndexWindow", "%p%"))
        self.action.setText(_translate("IndexWindow", "软件注册"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IndexWindow = QtWidgets.QMainWindow()
    ui = Ui_IndexWindow()
    ui.setupUi(IndexWindow)
    IndexWindow.show()
    sys.exit(app.exec_())
