# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Polly\Eric_Workspace\AutoConfigGUI\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(854, 474)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gbox_Browser = QtWidgets.QGroupBox(self.centralWidget)
        self.gbox_Browser.setGeometry(QtCore.QRect(60, 60, 741, 80))
        self.gbox_Browser.setObjectName("gbox_Browser")
        self.ledt_Browser = QtWidgets.QLineEdit(self.gbox_Browser)
        self.ledt_Browser.setGeometry(QtCore.QRect(30, 30, 601, 20))
        self.ledt_Browser.setReadOnly(True)
        self.ledt_Browser.setObjectName("ledt_Browser")
        self.btn_Browser = QtWidgets.QPushButton(self.gbox_Browser)
        self.btn_Browser.setGeometry(QtCore.QRect(640, 30, 75, 23))
        self.btn_Browser.setObjectName("btn_Browser")
        self.gbox_List = QtWidgets.QGroupBox(self.centralWidget)
        self.gbox_List.setGeometry(QtCore.QRect(60, 170, 191, 281))
        self.gbox_List.setObjectName("gbox_List")
        self.cbox_List = QtWidgets.QComboBox(self.gbox_List)
        self.cbox_List.setGeometry(QtCore.QRect(30, 30, 151, 22))
        self.cbox_List.setObjectName("cbox_List")
        self.cbox_List.addItem("")
        self.cbox_List.addItem("")
        self.cbox_List.addItem("")
        self.cbox_List.addItem("")
        self.gbox_MultiSelect = QtWidgets.QGroupBox(self.centralWidget)
        self.gbox_MultiSelect.setGeometry(QtCore.QRect(260, 170, 541, 281))
        self.gbox_MultiSelect.setObjectName("gbox_MultiSelect")
        self.btn_Add = QtWidgets.QToolButton(self.gbox_MultiSelect)
        self.btn_Add.setGeometry(QtCore.QRect(250, 120, 37, 18))
        self.btn_Add.setObjectName("btn_Add")
        self.btn_Del = QtWidgets.QToolButton(self.gbox_MultiSelect)
        self.btn_Del.setGeometry(QtCore.QRect(250, 170, 37, 18))
        self.btn_Del.setObjectName("btn_Del")
        self.list_Unselect = QtWidgets.QListWidget(self.gbox_MultiSelect)
        self.list_Unselect.setGeometry(QtCore.QRect(20, 30, 211, 231))
        self.list_Unselect.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_Unselect.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.list_Unselect.setObjectName("list_Unselect")
        item = QtWidgets.QListWidgetItem()
        self.list_Unselect.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_Unselect.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_Unselect.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_Unselect.addItem(item)
        self.list_Selected = QtWidgets.QListWidget(self.gbox_MultiSelect)
        self.list_Selected.setGeometry(QtCore.QRect(300, 30, 221, 231))
        self.list_Selected.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_Selected.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.list_Selected.setObjectName("list_Selected")
        item = QtWidgets.QListWidgetItem()
        self.list_Selected.addItem(item)
        self.btn_Export = QtWidgets.QPushButton(self.centralWidget)
        self.btn_Export.setGeometry(QtCore.QRect(700, 20, 101, 23))
        self.btn_Export.setObjectName("btn_Export")
        self.btn_Import = QtWidgets.QPushButton(self.centralWidget)
        self.btn_Import.setGeometry(QtCore.QRect(590, 20, 101, 23))
        self.btn_Import.setObjectName("btn_Import")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gbox_Browser.setTitle(_translate("MainWindow", "文件夹选择"))
        self.btn_Browser.setText(_translate("MainWindow", "浏览"))
        self.gbox_List.setTitle(_translate("MainWindow", "下拉列表选择"))
        self.cbox_List.setItemText(0, _translate("MainWindow", "File-1"))
        self.cbox_List.setItemText(1, _translate("MainWindow", "File-2"))
        self.cbox_List.setItemText(2, _translate("MainWindow", "File-3"))
        self.cbox_List.setItemText(3, _translate("MainWindow", "File-4"))
        self.gbox_MultiSelect.setTitle(_translate("MainWindow", "去冗余多选框"))
        self.btn_Add.setText(_translate("MainWindow", "->"))
        self.btn_Del.setText(_translate("MainWindow", "<-"))
        __sortingEnabled = self.list_Unselect.isSortingEnabled()
        self.list_Unselect.setSortingEnabled(False)
        item = self.list_Unselect.item(0)
        item.setText(_translate("MainWindow", "项目1"))
        item = self.list_Unselect.item(1)
        item.setText(_translate("MainWindow", "项目2"))
        item = self.list_Unselect.item(2)
        item.setText(_translate("MainWindow", "项目4"))
        item = self.list_Unselect.item(3)
        item.setText(_translate("MainWindow", "项目5"))
        self.list_Unselect.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.list_Selected.isSortingEnabled()
        self.list_Selected.setSortingEnabled(False)
        item = self.list_Selected.item(0)
        item.setText(_translate("MainWindow", "项目3"))
        self.list_Selected.setSortingEnabled(__sortingEnabled)
        self.btn_Export.setText(_translate("MainWindow", "生成配置文件"))
        self.btn_Import.setText(_translate("MainWindow", "导入配置文件"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
