# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Polly\Eric_Workspace\AutoConfigGUI\Register.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.setWindowModality(QtCore.Qt.ApplicationModal)
        Register.resize(366, 168)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Register)
        self.horizontalLayout_2.setContentsMargins(35, 20, 35, 20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter = QtWidgets.QSplitter(Register)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.formLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(0, 6, 0, 0)
        self.formLayout.setSpacing(8)
        self.formLayout.setObjectName("formLayout")
        self.lbl_number = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_number.sizePolicy().hasHeightForWidth())
        self.lbl_number.setSizePolicy(sizePolicy)
        self.lbl_number.setObjectName("lbl_number")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_number)
        self.ledt_number = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledt_number.sizePolicy().hasHeightForWidth())
        self.ledt_number.setSizePolicy(sizePolicy)
        self.ledt_number.setReadOnly(True)
        self.ledt_number.setObjectName("ledt_number")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ledt_number)
        self.lbl_username = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_username.sizePolicy().hasHeightForWidth())
        self.lbl_username.setSizePolicy(sizePolicy)
        self.lbl_username.setObjectName("lbl_username")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_username)
        self.ledt_username = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledt_username.sizePolicy().hasHeightForWidth())
        self.ledt_username.setSizePolicy(sizePolicy)
        self.ledt_username.setClearButtonEnabled(True)
        self.ledt_username.setObjectName("ledt_username")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ledt_username)
        self.lbl_email = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_email.sizePolicy().hasHeightForWidth())
        self.lbl_email.setSizePolicy(sizePolicy)
        self.lbl_email.setObjectName("lbl_email")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_email)
        self.ledt_email = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledt_email.sizePolicy().hasHeightForWidth())
        self.ledt_email.setSizePolicy(sizePolicy)
        self.ledt_email.setClearButtonEnabled(True)
        self.ledt_email.setObjectName("ledt_email")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ledt_email)
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_submit = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_submit.sizePolicy().hasHeightForWidth())
        self.btn_submit.setSizePolicy(sizePolicy)
        self.btn_submit.setObjectName("btn_submit")
        self.horizontalLayout.addWidget(self.btn_submit)
        self.btn_cannel = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cannel.sizePolicy().hasHeightForWidth())
        self.btn_cannel.setSizePolicy(sizePolicy)
        self.btn_cannel.setObjectName("btn_cannel")
        self.horizontalLayout.addWidget(self.btn_cannel)
        self.horizontalLayout_2.addWidget(self.splitter)
        self.lbl_username.setBuddy(self.ledt_username)
        self.lbl_email.setBuddy(self.ledt_email)

        self.retranslateUi(Register)
        self.btn_cannel.clicked.connect(Register.close)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Software Register"))
        self.lbl_number.setText(_translate("Register", "S/N"))
        self.lbl_username.setText(_translate("Register", "Username"))
        self.lbl_email.setText(_translate("Register", "Email"))
        self.btn_submit.setText(_translate("Register", "Submit"))
        self.btn_cannel.setText(_translate("Register", "Cannel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Register = QtWidgets.QDialog()
    ui = Ui_Register()
    ui.setupUi(Register)
    Register.show()
    sys.exit(app.exec_())
